### ISSUE TITLE
When deploying management resources, log analytics workspace is deployed in the wrong subscription

### ISSUE THREAD

**Issue by calexandre** [Azure/terraform-azurerm-caf-enterprise-scale#102]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

- **terraform**: `0.14.10`
- **azure provider**: `hashicorp/azurerm v2.58.0`
- **module**: `0.3.1`

### Description

As the title says, when deploying the management resources, the log analytics workspace (and maybe the security center aswell) may be deployed in the wrong subscription depending on which is client's active subscription (`az account show`).

We noticed this when trying to deploy management resources for the first time, and what actually happened is that the module/terraform was using the azure's current active subscription instead of the one defined in the `subscription_id_management` section - you can get the active subscription by using the following command: `az account show`.

No matter what value we set in the `subscription_id_management`, the terraform always ended deploying the log analytics workspace under the subscription the current client's context was set to.

The only workaround to ensure that the resources were deployed in the correct subscription was to set the current active subscription to the same configured in the `subscription_id_management` (`az account set --subscription="<subscription_id_management>"`)

Even after using the above workaround, you still need to keep the same active subscription, otherwise terraform will try deploy resources to the current active subscription.

**Steps to Reproduce**

1. Ensure you have at least **two** subscriptions to work with (they should be on the same tenant).
2. Set `subscription_id_management` to the subscription that you want to deploy your management resources.
3. Set your active subscription to a different subscription `az account set --subscription="some-other-subscription"`
4. Terraform `plan` & `apply` and the deploy will fail
5. Search through the azure portal and lookup where the log analytics workspace was deployed and confirm that it was deployed in the account's active subscription instead of the one defined in the `subscription_id_management`

**Comment by krowlandson** [comment]
Thank you for sharing your issue @calexandre 

This is unfortunately due to a limitation in Terraform (or specifically the azurerm provider), relating to the way the provider credentials associate your connection to Azure with a specific Subscription. As such, Terraform is unable to deploy resources across multiple Subscriptions using a single provider configuration.

You could work around this by breaking up your deployment into multiple instances of the module, ensuring each instance is using the correct Subscription as part of the provider configuration. One limitation I can think of right now is that by splitting the deployment like this, the policies associated with the `management` landing zone will have `enforcement_mode = false`. This is something we will need to give some more thought as to how best to handle.

As such, **our current recommendation** is to use the `Management` subscription within your provider configuration, deploying both `core` and `management` resources together through this Subscription.

For some additional context... The value specified in `subscription_id_management` is currently used to configure the data model only. This is used to set parameter values on specific Policy Assignments. When you set `deploy_management_resources` to true, you must also ensure you are running your module deployment against the management Subscription or you will observe the behaviour you mention above. In the near future, we expect to also use this value to move the specified Subscription into the `management` Management Group.

We have it on our backlog to document this more clearly, but I'll make sure this particular point is made more obvious and give this some more thought on whether there's anything else we can do to make this easier.

As we add more "landing zone solutions" to the module (e.g. identity and connectivity), it will become necessary to start breaking your deployment up because of these limitations. At this point we plan to publish an "accelerator" repository where we show the recommended approach for configuring the module to deploy against multiple Subscriptions using provider aliases. In the meantime, I hope this response helps to answer your question?

**Comment by calexandre** [comment]
Thank you for the explanation @krowlandson !
We actually ended up following your suggestion and fixed the `management` and `connectivity` subscription ids at the provider level.

For now, this is working for us:

```hcl
provider "azurerm" {
  subscription_id = local.subscriptions.management_subscription_id
  tenant_id       = local.tenant_id
  features {}
}

provider "azurerm" {
  alias           = "connectivity"
  subscription_id = local.subscriptions.connectivity_subscription_id
  tenant_id       = local.tenant_id
  features {}
}
```

**Comment by krowlandson** [comment]
Awesome, thank you for the update. I'll leave this issue open for now so we can address this when updating the documentation.

**Comment by Eslam10** [comment]
@krowlandson , I am trying to split the deployment into multiple instances for better arrangement of the deployment, and I came across this issue where the management resources will be deployed however the related security policies are not being applied `configure_management_resources.settings.security_center.enabled=true`. 
I assume this is related to what you mentioned on the comment above  for the `enforcement_mode = false`. any thoughts how this could be fixed ?
