### ISSUE TITLE
Documentation update to show permission requirements

### ISSUE THREAD

**Issue by gbr759** [Azure/terraform-azurerm-caf-enterprise-scale#145]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hi,

Would it be possible to update the documentation to include the permissions required in Azure AD / subscription level for the TF module to successfully run end-to-end?  Let's assume a full deployment with hub/spoke included.

The reason I ask is that we're doing lots of ES deployments at the moment, and generally customers will give us GA/tenant root owner levels, but it's (understandably) becoming more common for customers to ask us for more granular permissions, be it for accounts or SPNs.  At the moment I'm unsure for an end-to-end deployment and I'm sure others have been asked similar questions.

Thanks

**Comment by krowlandson** [comment]
You should be able to view a preview of the proposed new page covering this issue here:
[[User Guide] Module Permissions](https://github.com/krowlandson/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Module-Permissions)

Please let me know if that helps and whether you would like to see additional information.

As a quick additional note, we are avoiding going to the specifics of individual [Actions](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-definitions#actions) due to the fact that we advise customers to use built-in roles wherever possible.

**Comment by gbr759** [comment]
Thanks for this Kevin, much appreciate you putting the time in.
