### ISSUE TITLE
Moved Subscription to Enterprise scale cause Deployment to fail 

### ISSUE THREAD

**Issue by benoitedi** [Azure/terraform-azurerm-caf-enterprise-scale#160]
Hi,

If you use the plugin here to deploy your Management group structure and move your subscription manually (existing one), for any change you do to the management groups or enterprise Scale, the code will want to remove the subscription from the management groups.
Example of a plan:

module.enterprise_scale.azurerm_management_group.level_4["/providers/Microsoft.Management/managementGroups/mgmt-nprod"] will be updated in-place
  ~ resource "azurerm_management_group" "level_4" {
        id                         = "/providers/Microsoft.Management/managementGroups/mgmt-nprod"
        name                       = "mgmt-nprod"
      ~ subscription_ids           = [
          - XXXXXXXXXXXXXXXXXX",
        ]
        # (3 unchanged attributes hidden)
    }

As you can see below the plan show that Sub XXXXXXXXXX would be removed ( the little "-" in front of the sub ID)

The apply will then result in:

│ Error: unable to de-associate Subscription "XXXXXXXXXXXXXXXXXX" from Management Group "mgmt-nprod": managementgroups.SubscriptionsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service
returned an error. Status=400 Code="BadRequest" Message="Permission to write and delete on resources of type 'Microsoft.Authorization/roleAssignments' is required on the subscription or its ancestors." Details=[{"raw":"Subscription ID: '/subscriptions/XXXXXXXXXXXXXXXXX'"}]

PS: We do not want the subscription to be moved in that case. I was only running a refresh of the role assignments, but we move manually Subscription which already existed into the new Enterprise Scale Management groups.

Thank you

**Comment by jtracey93** [comment]
Thanks @gbr759 for replying here 👍

Also to add to this @benoitedi - When using Terraform to deploy and manage your estate, you should not make changes outside of Terraform to those resoruces which it manages - as the state will get out if sync.

As @gbr759 said, your SPN/User should have permissions over the scope "/" (Tenant Root Group) so it should be able to move subs into the hierarchy no matter where they are in the tenant.

Let us know if this helps or you need anything 👍

**Comment by benoitedi** [comment]
Hi,
Thank you both @jtracey93 @gbr759 

While the issue point to access right, it is not my problem. I can fix so and do agree TFE should drive everything. But, we are not managing the subscription via that plugin / code. It is another terraform code doing it as we have some governance to do on those.

What I wonder would be more if Enterprise Scale could ignore the subscription as it does not managing them at that level.

Hope this make sense.

**Comment by jtracey93** [comment]
Hi @benoitedi,

This module will only manage susbcriptions within the Management Group hierarchy it deploys - e.g. Contoso and below

So if the Subscriptions are at the Tenant Root Group (default) or in another hierarchy outside of the "Contoso" hierarchy then that would achieve your goal of this module not managing them/ignoring them.

Does that help?

**Comment by benoitedi** [comment]
Hi @jtracey93 ,
I understand that part, but adding a subscription within Enterprise Scale required to add it to the configuration of the landing zone in which it will reside. This mean that if we were to add any number of subscription, we will have to change the enterprise scale code to reflect it.

While this is well and good, any miss subscription could potentially be remove from the Management group it should be in. This could have an impact on Policy / RBAC and so on.

I do appreciate that running a plan before an apply would help identifying the missing subscription.

I wonder if it is possible to not have this hardcoded link between the management group and the underline subscription within the code.

Hope this make sense

**Comment by jtracey93** [comment]
Hi @benoitedi,

This feels similar to issue #24 that we had a similar discussion on before, please review and let me know if you agree.

This is just one of those items that by using Terraform becomes something you have to cater for due to the way it is managing state.

As mentioned in #24 and above, by [setting your default management group](https://docs.microsoft.com/en-us/azure/governance/management-groups/how-to/protect-resource-hierarchy) to somewhere outside of what this module deploys for its Management Group hierarchy - e.g. Tenant Root MG (which is default on all tenants) or a new "Provisioning" management group outside of the ESLZ hierarchy and a child of the Tenant Root MG, you should be able to accomplish your ask.

The "Provisioning MG" outside of the ESLZ hierarchy is the better approach as you can assign a base set of RBAC and Policies to it to ensure it is compliant from the start. And then you can bring it into your ESLZ hierarchy when ready.

By doing this it wouldn't be noticed by a Terraform `plan` and therefore is something you can cater for as part of your Subscription vending process.

Does this help?

Thanks

Jack

**Comment by benoitedi** [comment]
Hi,

@jtracey93 - Thank you - Happy to close the issue :)
