### ISSUE TITLE
Feature Request: Use of different SPN

### ISSUE THREAD

**Issue by benoitedi** [Azure/terraform-azurerm-caf-enterprise-scale#162]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

Would it be possible to have different SP to run enterprise Scale:

- one for Managemnt group
- one for RBAC
- one for Policy

**Describe the solution you'd like**

I wonder if we could use different  azurerm provider based on what the action is going to be. This will allow to have one provider per task and so different SPs rather than a global SP. 
We normally use 3 different SPs to cover the Enterprise Scale requirements, but for now I do not see a way to provide the 3 SPs.

**Additional context**
We do separation of duties and are driven to limit SP to one duty.

**Comment by jtracey93** [comment]
Hi @benoitedi,

They way that Terraform works would mean that each of these would have to be a seperate `init`, `plan`, `apply` and state and that adds overhead that generally users don't want to manage and being honest, no customer I have worked with has split it like you suggested above.

The whole idea of Enterprise Scale is to setup and control the "platform" for Azure within an Azure AD Tenant, to do this it does require a high level of permissions, but this is to enable it to create and manage the tenant level resources.

I would recommend reviewing the new document in the wiki we published about the permissions required for this module: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Module-Permissions

Also another possibility with this module is to use nesting to control seperate Management Group hierarchies, check out this wiki article here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Using-Module-Nesting

Does that makes sense and help?

Due to the way Terraform works, we could not add support for splitting the deployment of different resources via different SPNs within a single terraform `plan`.

**Comment by benoitedi** [comment]
Hi @jtracey93,

I am not talking about 3 different init / plan / apply, just the possibility to have 3 azurerm provider within the same workspace  call using the configuration aliases.

We do this all the time when we need RBAC and contributor access. We create 2 azurerm provider and use aliases to different them on call. This do not required a separate init / plan or apply. It is all in one workspace for Terraform.

An example of config is:
`provider "azurerm" {
  subscription_id            = var.user_subscription_id
  client_id                  = var.user_client_id
  client_secret              = var.user_client_secret
  tenant_id                  = var.user_tenant_id
  skip_provider_registration = true
  features {}
}

provider "azurerm" {
  alias                      = "hub"
  subscription_id            = var.user_subscription_hub_id
  client_id                  = var.user_client_hub_id
  client_secret              = var.user_client_hub_secret
  tenant_id                  = var.user_tenant_id
  skip_provider_registration = true
  features {}
}`

In that case we have 2 azurerm provider targeting 2 subscriptions with 2 SPs. We then can do:
`data "azurerm_subscription" "subscription" {
}

data "azurerm_subscription" "subscription_hub" {
  provider        = **azurerm.hub**
  subscription_id = local.hub_subscription_id
}`

Hope this make more sense :)

**Comment by jtracey93** [comment]
Hi @benoitedi,

That does make more sense and we do have 3 `configuration_aliases` available in the module as of the `v0.4.0` release all documented here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Provider-Configuration

But the resoruces you referred to (Management Groups, Policy, RBAC etc.) are all "tenant" level resoruces which dont pin to a subscription, therefore this is the `core` alias within the module as we have to have a subscription available for Terraform to authenticate to Azure.

Does that help?

Many Thanks

Jack 👍

**Comment by benoitedi** [comment]
Hi @jtracey93 

So it is also possible to use that approach for access right / RBAC separation.

In our case we have 3 SPs with different RBAC or access
- one for Management group - Only can do Management group / create / delete and move sub
- one for RBAC - Only can do User Administration
- one for Policy - Only can create and assign policy

If in a Terraform workspace we needed  those 3 actions we would normally create 3 AzureRM Provider that way:

`provider "azurerm" {
alias = "policy"
subscription_id = var.user_subscription_id
**client_id = var.user_client_id
client_secret = var.user_client_secret**
tenant_id = var.user_tenant_id
skip_provider_registration = true
features {}
}

provider "azurerm" {
alias = "mgmt"
subscription_id = var.user_subscription_id
**client_id = var.user_client_mgmt_id
client_secret = var.user_client_mgmt_secret**
tenant_id = var.user_tenant_id
skip_provider_registration = true
features {}
}

provider "azurerm" {
alias = "rbac"
subscription_id = var.user_subscription_id
**client_id = var.user_client_rbac_id
client_secret = var.user_client_rbac_secret**
tenant_id = var.user_tenant_id
skip_provider_registration = true
features {}
}`

Then as a below show you we will just call the right provider via Alias based on what the resource is doing or need access to.

Does this helps?

**Comment by jtracey93** [comment]
Hi @benoitedi,

This is something you could do, but the module today does not support this split in the providers, we split it as per the link provided above: `core, management, connectivity` 

Splitting the way you are looking towards would also be a little more complicated with ESLZ as a policy assignment for a DeployIfNotExists policy will create a System Assigned Managed Identity and then you need to grant it RBAC over the desired scope so it will work. 

Whilst possible with the split you suggest, outside of the module, it would be a little more complicated than most require.

Out of interest for the 3 SPNs you mention above, would they have custom or tightly scoped RBAC roles assigned so none of them overlap. e.g. the Management Group one only has permissions to do Management Group actions and nothing else like a generic `contributor`?

I don't think this is something we would look to add to the module at this time, but would be interested to understand more of the reasoning behind the requirement. Also would be interested for @krowlandson's input on this issue when he returns from holiday.

Thanks

Jack

**Comment by krowlandson** [comment]
Thank you @benoitedi for raising this issue, and @jtracey93 for helping whilst I've been out of office.

This is indeed an interesting ask and I've been giving it careful consideration.

As @jtracey93 says, the module is already designed to utilise 3 providers for `core`, `management` and `connectivity`. This is to allow a single instance of the module to deploy resources into the 2 different subscriptions for `management` and `connectivity`, with an optional 3rd for `core`. This provides a good balance, and allows customers to also associate API calls for `core` resources with a different Subscription to minimise the risk of rate limiting. We generally find that setting `-parallelism=50` is about the highest you can go before getting rate limited by the policy API.

Whilst it would be technically possible within the module to create the proposed split, this would add unnecessary complexity for most of our users due to the need to declare all providers within the `providers` object. There's also no guidance within CAF or Enterprise-scale which would recommend the proposed approach.

We recommend using a single identity to build the Enterprise-scale platform and ensure this is run from within a secured pipeline. This is because the SPN used to create a Management Group is automatically granted `Owner` permissions on that Management Group, and therefore has "all permissions" over "all child resources". This is what we want from a governance perspective, as it allows that SPN to be used to enforce any desired settings across the platform.

When we discuss this with customers, our recommendation is to monitor the account for unusual / unexpected activity (i.e. using SIEM tooling). This is [documented in the Wiki](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Module-Permissions).

Closing this issue, as this isn't something we are likely to implement and our guidance is already clearly documented.
