### ISSUE TITLE
Feature Request- Provide instructions on using MI instead of SPN

### ISSUE THREAD

**Issue by Ashley72** [Azure/terraform-azurerm-caf-enterprise-scale#163]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be good to have some instructions on setting up PipeLines with Managed Identity instead of using SPN as this is sometimes a preferred way to work depending on company policies and use of AAD

**Comment by jtracey93** [comment]
Good ask @Ashley72, We will look into this during our documentation updates that are happening as we speak.

For now, Terraform has some good guidance on MSI usage for the azurerm provider here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/managed_service_identity

**Comment by krowlandson** [comment]
Hi @Ashley72, as this is specific to how to run Terraform and configure the provider we are not likely to cover this within the module instructions, otherwise we just end up duplicating all of the provider documentation in our examples.

Instead, our plan is to create an accelerator repository which provides a reference deployment using pipelines for deployment.

Hopefully this will provide some of the coverage you are looking for but is unlikely to be the specific scenario you've asked for as using MSIs within pipelines is quite an advanced scenario which requires custom runners. Our intent is to create something which is accessible to everyone with minimal additional overhead.
