### ISSUE TITLE
Change Default Naming Convention for Resources

### ISSUE THREAD

**Issue by Eslam10** [Azure/terraform-azurerm-caf-enterprise-scale#165]
We would like to follow the naming convention recommended by Microsoft for ES-CAF as described here https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming.
The default naming convention for most of the resources being deployed by this module is not following the above naming convention, as per the module code, it's possible to do that using the "advanced" variable, however the below disclaimer is also there in the module documentation!
- Use of the advanced setting is currently undocumented and experimental. Please be aware that using this setting may result in future breaking changes.
So, how can we follow any custom naming convention we need and stay compliant with this module for future releases ?

**Comment by jtracey93** [comment]
Hey @Eslam10,

Thanks for the great feedback and we do certainly hear you 👍

We have this open on our backlog to make this consistent and customisable across all implementations of ESLZ (ARM, Bicep (when released), Terraform etc.).

I'll leave this open to help us track and ensure we come back to this when we have got a further update on the wider naming standard piece.

However today for this module, you are correct the `advanced` setting is currently the way to do this but is undocumented and experimental as of the current `v0.4.0` release. 

This is something we are working to make available and non-experimental soon in an upcoming release but we want to ensure the schema of the input variable for the `advanced` block is consistent across the resource types it will be available for so that it is easy to use. - @krowlandson please feel free to provide any further insights here around timelines and plans for `advanced`.

Thanks

Jack

**Linking to other issues for visibility/tracking:**
- https://github.com/Azure/Enterprise-Scale/issues/674
- https://github.com/Azure/Enterprise-Scale/issues/545
- https://github.com/Azure/Enterprise-Scale/issues/781
- https://github.com/Azure/Enterprise-Scale/issues/23
- https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/73
- **Internal Backlog Item Tracking Number:** SE Backlog Item 69049

**Comment by Eslam10** [comment]
Hi @jtracey93,

Thank you for your quick response :) for now we will continue using this `advanced` settings.

Thanks,
Eslam

**Comment by krowlandson** [comment]
Going to close this for now, as we don't currently plan to add a new feature to change naming beyond the current method via "advanced". We will however add documentation of the "advanced" setting options so our project boards.
