### ISSUE TITLE
Policy definition not found

### ISSUE THREAD

**Issue by sagar-dholakia** [Azure/terraform-azurerm-caf-enterprise-scale#197]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:  v1.0.1 for linux_amd64

**azure provider**: hashicorp/azurerm v2.66.0

**module**: archetypes

### Description

When assigning policies that are built in to azure caf, some of the policy definitions don't seem to be found. 

<details>
<summary>Error: policy definition not found</summary>

```bash
╷
│ Error: reading Policy Definition "Deploy-ASC-Defender-ACR": policy.DefinitionsClient#GetBuiltIn: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicyDefinitionNotFound" Message="The policy definition 'Deploy-ASC-Defender-ACR' could not be found."
│ 
│   with module.enterprise_scale.data.azurerm_policy_definition.external_lookup["/providers/Microsoft.Management/managementgroups/lvfscanary/providers/Microsoft.Authorization/policyDefinitions/Deploy-ASC-Defender-ACR"],
│   on /home/vscode/.terraform.cache/modules/enterprise_scale/locals.policy_assignments.tf line 152, in data "azurerm_policy_definition" "external_lookup":
│  152: data "azurerm_policy_definition" "external_lookup" {
│ 
╵
```
</details>

<details>
<summary>archetype_extension_es_root.json</summary>

```json
{
  "extend_es_root": {
      "policy_assignments": [
        "Deploy-ASC-Defender-ACR"
      ],
      "policy_definitions": [
      ],
      "policy_set_definitions": [
      ],
      "role_definitions": [
      ],
      "archetype_config": {
          "parameters": {
            "Deploy-ASC-Defender-ACR": {
              "effect": "Disabled",
              "pricingTier": "Standard"
            }
          },
          "access_control": {}
      }
  }
}
```
</details>

**Steps to Reproduce**

1. deploy/apply caf_solution caf_eslz with no policy assignments (we use the following command)
```
rover -lz /tf/caf/landingzones/caf_solution/add-ons/caf_eslz -tfstate foundations.tfstate -var-folder /tf/caf/configuration/canary -parallelism 10 -level level1 -env canary -a plan
```
2. assign custom caf policy Deploy-ASC-Defender-ACR (as per archetype_extension_es_root.json above)
3. run plan and get error

**Screenshots**

Deploy ASC Defender ACR policy is in azure:
![image](https://user-images.githubusercontent.com/67733963/139232329-08b565ee-e035-43a1-94a5-ea51e3f8b34f.png)

**Comment by sagar-dholakia** [comment]
Thanks for the help :) 
From the caf-terraform-landingzone repo, we forked from master branch at this particular commit: 7c7ba96361c214d70362d4b4ae2f57ba498a7ce4 and then made some changes to it over the course of a few months. 

Some of these changes were to the files within caf_eslz. (below shows what we have currently)

<details>
<summary>enterprise_scale.tf</summary>

```
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.3.3"

library_path               = "${path.root}/lib"
```
</details>

<details>
<summary>main.tf</summary>

```
required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.66.0"
    }
  }
  required_version = "1.0.1"
```
</details>

other changes include things like adding support to deploy things like log analytics to subscriptions, adding more outputs. 

would you need a detailed list of the changes made?

**Comment by krowlandson** [comment]
Thank you for the additional information @sagar-dholakia 

As the [caf-terraform-landingzones](https://github.com/Azure/caf-terraform-landingzones) implementation is quite specific in the way it works, there may be a few things to validate.

Not likely to make a difference to this specific scenario, but we would recommend updating to the latest version of the module:

![GitHub release (latest SemVer)](https://img.shields.io/github/v/release/Azure/terraform-azurerm-caf-enterprise-scale?style=flat&logo=github)

> You may also need to update your provider version too.

Specific to your issue, it looks like the module is not able to correctly identify the target Policy Definition as being one deployed by the module. My initial thinking was that you may have something wrong within the module configuration, but I'm now wondering whether the `policyDefinitionId` value is incorrect within the Policy Assignment template.

As Terraform is case sensitive, this value must **EXACTLY** match the value expected by the module, otherwise it will perform a dynamic lookup against the platform. This is part of the module determining which role(s) must be assigned to the managed identity when using DINE or modify effects.

Would you mind updating the following line in your Policy Assignment and try again please?

```json
    "policyDefinitionId": "${root_scope_resource_id}/providers/Microsoft.Authorization/policyDefinitions/Deploy-ASC-Defender-ACR",
```

The template variable `root_scope_resource_id` will be dynamically replaced with the expected value for this to match up with what the module expects.

If you have multiple custom Policy Assignments, you may need to check the others too.

**Comment by sagar-dholakia** [comment]
The change that you've given certainly worked for the policy that was not being found. I will make this change to other policies that are having the same issue and let you know. 

One thing that is odd is that I copied the "Definition ID" from the portal for each policy, like the one below. So the portal might not have the right case when showing the ID. 
![image](https://user-images.githubusercontent.com/67733963/140723322-bf0c1122-77cd-44f6-857d-1579feca3ba7.png)

**Comment by krowlandson** [comment]
That's great to hear @sagar-dholakia... thank you for confirming.

Unfortunately (like most Microsoft products) Azure is not strictly case-sensitive in many areas, and in some cases is actually case-inconsistent.

As Terraform is written in [Go](https://golang.org/), it is 100% case-sensitive so we had to make a decision on what we considered to the "the correct casing" for everything within the module.

We generally try to follow what is publicly documented, and in most cases this is `camelCase`. However there are always some exceptions. The crucial thing in most cases is to be consistent with whatever you set within your configuration. In this specific case, as the policy definition(s) are being deployed by the module, the format of the full Resource ID is critical to get a case-sensitive match in the data model.

If this was genuinely a Policy Definition ID for a definition NOT deployed by the module, I don't think this would matter as we would use whatever case you provided and just perform a lookup of the definition from Azure. This is effectively what's happening when you get the case wrong, but in your case the definition doesn't yet exist, hence the error.

I'm going to close this issue as I believe this should resolve your issue but please re-open if you have further related problems.
