### ISSUE TITLE
Enabling Defender for specific subscriptions or management groups instead of everywhere

### ISSUE THREAD

**Issue by sean-kang** [Azure/terraform-azurerm-caf-enterprise-scale#206]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems that the scope of the assignment that enables Defender is "root" in this Terraform template. This does not suit our organization because we do not want Defender to be enabled in Sandbox management group in order to avoid the unnecessary expense in non-production resources. Is there a way to enable Defender for specific subscriptions or management groups?

**Comment by krowlandson** [comment]
Thank you for the question @sean-kang 

Our recommendation in this scenario would be to create a copy of the Policy Assignment in your custom library (as specified by the [`library_path`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-library_path) input variable) and add the Sandbox Management Group to the `notScopes` value.

But if you really want to change the scope, this is where the ability to edit archetype definitions comes into play, as documented on the Wiki in the following example:
[[Examples] Expand built in archetype definitions](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions)

To cover your specific scenario, you would create the following two files and place them in your custom library.

`lib/archetype_exclusion_es_root.tmpl.json`

```json
{
  "exclude_es_root": {
    "policy_assignments": [
      "Deploy-ASC-Configuration"
    ],
    "policy_definitions": [],
    "policy_set_definitions": [],
    "role_definitions": [],
    "archetype_config": {
      "parameters": {},
      "access_control": {}
    }
  }
}
```

`lib/archetype_extend_es_landing_zones.tmpl.json`

```json
{
  "extend_es_landing_zones": {
    "policy_assignments": [
      "Deploy-ASC-Configuration"
    ],
    "policy_definitions": [],
    "policy_set_definitions": [],
    "role_definitions": [],
    "archetype_config": {
      "parameters": {},
      "access_control": {}
    }
  }
}
```

Note you will need to provide all of the [required parameters](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_asc_configuration.tmpl.json#L9-L52) to configure this Policy Assignment at the new scope as the configuration included through [`configure_management_resources`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_management_resources) will no longer work on this Policy Assignment due to the change of scope.

Hope this helps but please let us know if you have further questions regarding this.

**Comment by sean-kang** [comment]
I copied the policy assignment to our library and edited the `notScopes` as recommended and it seems to be working. I added the following line.

`lib/policy_assignments/policy_assignment_es_deploy_asc_configuration.tmpl.json`

`
"notScopes": [ "${root_scope_resource_id}-sandboxes" ]
`

Thank you for your help.
