### ISSUE TITLE
Unable to set metricsEnabled to True for KeyVaultDeployDiagnosticLogDeployLogAnalytics

### ISSUE THREAD

**Issue by samiwel** [Azure/terraform-azurerm-caf-enterprise-scale#207]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.0.7

**azure provider**: v2.78.0

**module**: 1.0.0

### Description

**Describe the bug**

We are trying to achieve compliance with UK Official and NHS policy initiatives which are assigned at the root of our CAF enterprise scale deployment.

We are not compliant with a built in policy `Audit diagnostic setting` due to missing the `"metricsEnabled": "True"`  parameter on the built in policy `KeyVaultDeployDiagnosticLogDeployLogAnalytics` which is in the policy set definition `Deploy-Diagnostics-LogAnalytics`.

**Steps to Reproduce**

1. Deploy CAF
1. Apply UK Official and NHS initiative at the root of the CAF deployment.
1. Create a KeyVault instance under a subscription in the Identity management group.
1. Remediate the non-compliance for the aforementioned policy.
1. The created diagnostic setting `setbypolicy` does not have all metrics checked.

**Screenshots**

**Additional context**

We have tried to override the CAF policy configuration by creating a customised version of the policy set and policy assignment (which allows setting the metricsEnabled parameter) and extending the archetype at the Management management group to apply the custom assignment. We also added an exclusion to try and remove the CAF module supplied assignment at the Management group `Deploy-Resource-Diag` which is being inherited from the root - but this did not seem to work.

**Comment by krowlandson** [comment]
Thank you for logging this issue @samiwel 

All of our policies are sourced from the [Azure/Enterprise-Scale](https://github.com/Azure/enterprise-scale) repository. As such I will raise an issue there to add this to the Policy Set Definition and we will update this on the following release in our module.

In the meantime, please create a custom copy of the Policy Set Definition in your `lib` folder and make the addition needed. I appreciate this isn't your preferred approach (as discussed in #208), but this is also why we provided this capability to allow for customers to make such amendments without being tied to our development cycles.

**Comment by samiwel** [comment]
Thank you, @krowlandson. The custom policy set definition should be a workable solution for us in the short term. Is there some way that we can utilise the exclusion functionality of the module to prevent an assignment being applied at the root management group from being applied at the management landing zone? We would want to apply our custom definition set at the management landing zone, but would prefer to use the vanilla assignments in all other locations until we run into a similar need to customise.

As mentioned above we created a file archetype_exclusion_es_management.tmpl.json in the `lib` folder. With the following contents:

```
{
  "exclude_es_management": {
    "policy_assignments": ["Deploy-Resource-Diag"],
    "policy_definitions": [],
    "policy_set_definitions": [],
    "role_definitions": [],
    "archetype_config": {
      "parameters": {},
      "access_control": {}
    }
  }
}
```
But we end up with two assignments after an apply. Our custom assignment and the inherited one.

**Comment by krowlandson** [comment]
@samiwel, assuming you want to just remove this Policy Assignment, you're pretty close with your thinking above. To remove this assignment you need to create the exclusion at the scope where the original assignment is created, not at a lower scope where it has been inherited.

To do this, simply target your exclusion template at `es_root` instead of `es_management` (remembering to use the `exclude_` prefix as per your example.

Alternatively, if you still would like to have the assignment at the `root` scope, at would like to create an exception for the `management` scope, copy the Policy Assignment template to your custom `lib` folder and add the `management` scope to the `notScopes` value. For example:

```hcl
{
  "name": "Deploy-Resource-Diag",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2019-09-01",
  "properties": {
    "description": "Ensures that Azure resources are configured to forward diagnostic logs and metrics to an Azure Log Analytics workspace.",
    "displayName": "Deploy-Resource-Diag",
    "notScopes": [
      "${root_scope_resource_id}-management"
    ],
    "parameters": {
      "logAnalytics": {
        "value": "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/${root_scope_id}-mgmt/providers/Microsoft.OperationalInsights/workspaces/${root_scope_id}-la"
      }
    },
    "policyDefinitionId": "${root_scope_resource_id}/providers/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics",
    "scope": "${current_scope_resource_id}",
    "enforcementMode": null
  },
  "location": "${default_location}",
  "identity": {
    "type": "SystemAssigned"
  }
}
```

Regarding the `00000000-0000-0000-0000-000000000000` Subscription ID in the assignment parameters, this is a default value used when `subscription_id_management` hasn't been declared. Adding a value to this input will update all Policy Assignments needing this value.

Just to check, what it your reasoning for wanting the different assignment at only this scope?

**Comment by samiwel** [comment]
Thanks @krowlandson that's really helpful. I wasn't aware of the `notScopes` property but that looks like it might be a way to achieve what we are trying to do.

> Just to check, what it your reasoning for wanting the different assignment at only this scope?

To be honest, the need to apply the assignment at the management landing zone is an assumption on our part. We are declaring a `subscription_id_management` in the CAF module and I'm pretty sure that when we tested adding the custom assignment to the root management group, it didn't replace the `00000000-0000-0000-0000-000000000000` value with the management subscription Id. But I'll re-test this to confirm that behaviour.

**Comment by samiwel** [comment]
HI @krowlandson  We re-tested this morning and found that when the built-in `Deploy-Resource-Diag` assignment is deployed by the CAF module, the management subscription Id get's supplied into the `logAnalytics` parameter as expected. However if we extend with our custom assignment at the `es_root` level (copy and paste of the same assignment) the management subscription Id does not get substituted into the `logAnalytics` parameter. Any ideas why this might be?

**Comment by krowlandson** [comment]
> HI @krowlandson Kevin Rowlandson FTE We re-tested this morning and found that when the built-in `Deploy-Resource-Diag` assignment is deployed by the CAF module, the management subscription Id get's supplied into the `logAnalytics` parameter as expected. However if we extend with our custom assignment at the `es_root` level (copy and paste of the same assignment) the management subscription Id does not get substituted into the `logAnalytics` parameter. Any ideas why this might be?

Are you able to provide a code sample so we can try to debug this please?

**Comment by samiwel** [comment]
Certainly, [here's a Gist with our configuration](https://gist.github.com/samiwel/e06b70d33a5725ea9fb7efdfd59bde72) to reproduce we just place these in the `lib` folder. Note we're excluding the built-in assignment at the root and applying our custom assignment pointing at our custom policy set definition (which we've amended by adding the `metricsEnabled` parameter). When we apply this configuration the management landing zone subscription Id is not substituted in for to the `logAnalytics` workspace parameter.

**Comment by krowlandson** [comment]
Thank you for your patience investigating this issue. I appreciate this can be a bit tricky to get right the first time.

Looking at the Gist, I think it would be useful to be aware of the following behaviours of the module:

- When we set “managed” values on a number of our policies, we are doing so by creating input parameters for the Policy Assignments based on their names and the scope at which they're being assigned. In the case of the `Deploy-Resource-Diag` Policy Assignment, this can be seen in the code here:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4c64874539456b3596fd3c6030d114693258bf04/modules/management/locals.tf#L219-L221
- If you replace the Policy Assignment template with your own version with the same name, you will be able to use these input parameters as originally intended, but are also limited to these being the only values you can input.
- If you create your own Policy Assignments (with new names), the module has no way of knowing to map these values to the input parameters, so you must provide them yourself.

In this particular scenario, you will need to provide the Policy Assignment with a valid Log Analytics workspace ID.

Because you are making these amendments to the default `es_root` archetype and at the `root` scope, you would need to add the following block of code to your module declaration:

```hcl
module "enterprise_scale" {

# existing code

  archetype_config_overrides = {
    root = {
      archetype_id   = "es_root"
      parameters     = {
        "Custom-Deploy-Res-Diag" = {
          logAnalytics = "" # <---- Enter your Log Analytics workspace ID here
        }
      }
      access_control = {}
    }
  }

}
```

This should ensure that the correct value gets assigned to your Policy Assignment.

Just to note, we are looking at options to make this easier (and more obvious to configure).

If you would like to better understand how this works under the hood, we do the following (looking primarily at the context of the `root` Management Group:

1. We create a default object defining the default archetype config for each of the default Management Groups:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4c64874539456b3596fd3c6030d114693258bf04/locals.management_groups.tf#L15-L19
2. Then we create a map of the customer provided overrides:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4c64874539456b3596fd3c6030d114693258bf04/locals.management_groups.tf#L86-L89
3. Which are then merged into a base configuration object:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4c64874539456b3596fd3c6030d114693258bf04/locals.management_groups.tf#L90-L93
4. As part of determining the archetype configuration for each Management Group (using the archetype sub-module), we merge the "managed" values set by the `connectivity`, `identity` and `management` sub-modules with the base configuration object from above:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4c64874539456b3596fd3c6030d114693258bf04/locals.management_groups.tf#L283-L301

Effectively, by providing a configuration block as suggested earlier, you are setting a custom input which takes priority on line `297` of the merge process above.

Hopefully this description helps you to fix your problem and better understand how this works 😄

**Comment by krowlandson** [comment]
Added to release:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/releases/tag/v1.1.2

**Comment by krowlandson** [comment]
@samiwel... hopefully the latest additions for release [`v1.1.2`](Added to release:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/releases/tag/v1.1.2) should make this a bit easier for you to achieve some of the above.
