### ISSUE TITLE
Error using spoke_virtual_network_resource_ids to deploy peering

### ISSUE THREAD

**Issue by freddesrochers** [Azure/terraform-azurerm-caf-enterprise-scale#213]
**Describe the bug**
Hi,

i try to deploy my peering with the enterprise scale. I have a module where i deploy my vnet fort he perimeter zone. I want to use the id of that VNET and add it to my file "enterprisescale-settings.connectivity.tf"

 spoke_virtual_network_resource_ids      = [**module.landingzone.Vnet_Enligne_Cace_id**]
enable_outbound_virtual_network_peering = true

i got the following error: 
`│ Error: Invalid for_each argument
│
│   on .terraform\modules\enterprise_scale\resources.connectivity.tf line 379, in resource "azurerm_private_dns_zone_virtual_network_link" "connectivity":
│  379:   for_each = local.azurerm_private_dns_zone_virtual_network_link_connectivity
│     ├────────────────
│     │ local.azurerm_private_dns_zone_virtual_network_link_connectivity will be known only after apply
│
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply 
│ only the resources that the for_each depends on.
╵
╷
│ Error: Invalid for_each argument
│
│   on .terraform\modules\enterprise_scale\resources.connectivity.tf line 403, in resource "azurerm_virtual_network_peering" "connectivity":
│  403:   for_each = local.azurerm_virtual_network_peering_connectivity
│     ├────────────────
│     │ local.azurerm_virtual_network_peering_connectivity will be known only after apply
│
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply 
│ only the resources that the for_each depends on.`

I am not sure what to do with it. Is it the right way to setup network peering between 2 vnet ?

**Steps to reproduce**

1. module\landingzone\vnets.tf
`resource "azurerm_virtual_network" "VNET_Enligne_canacentral_name" {
name     = var.VNET_Enligne_canadacentral_name
location = var.locationCanadaCentral
address_space = ["xxxxx"]
resource_group_name = var.RG_Enligne_Canadacentral_name
tags = var.tags_ressources_Enligne
}`

2. module\landingzone\outputs.tf
`output "Vnet_Enligne_Cace_id" {
    #value = azurerm_network_security_group.nsg_AzureBastion_Canadaeast.id
    value = azurerm_virtual_network.VNET_Enligne_canacentral_name.id 
    description="ID du Vnet de service en ligne canada central"
}`

3.enterprisescale-settings.connectivity.tf
`spoke_virtual_network_resource_ids      = [module.landingzone.Vnet_Enligne_Cace_id]
enable_outbound_virtual_network_peering = true`

**Screenshots**

![image](https://user-images.githubusercontent.com/52010467/142661204-3d9990b8-e8a9-48f5-ad76-aba5a89f6694.png)

**Comment by krowlandson** [comment]
@freddesrochers, thank you for logging this issue, and great to see you are making use of some of these networking features!

In this particular case, the important part of the error message is:

> The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created.

Within the module, we use the Resource ID of each resource being created as the `key` within each `for_each` loop used to determine the resources to be created. Unfortunately there are some [known limitations](https://www.terraform.io/docs/language/meta-arguments/for_each.html#limitations-on-values-used-in-for_each) associated with the `for_each` loop, and this scenario is one of them.

In this case, we are using the Resource ID of each spoke Virtual Network to determine the `azurerm_private_dns_zone_virtual_network_link` and `azurerm_virtual_network_peering` resources to be created. Because you are creating these spoke Virtual Networks within the same deployment, Terraform is unable to safely determine whether these resources should be created until the Resource ID is output by the successful creation of this network.

Our recommended workaround is to ensure the input for this settings doesn't rely on dynamic values. This can be done using one of the following approaches, although there may be others:

- Provide the resource ID of your spoke Virtual Networks as static string values within the list. Resource IDs in Azure are deterministic, so you can always work out what it will be).
- Deploy the spoke network in a different deployment, and use the outputs of that deployment as inputs to the `caf-enterprise-scale` module using the `terraform_remote_state` data resource to read them in.

I appreciate this isn't ideal, but this seems to be a limitation within Terraform and something we have been unable to work around without breaking our [Terraform] resource naming approach.

Hope this helps?

**Comment by krowlandson** [comment]
Linking to #233 and closing
