### ISSUE TITLE
Bug Report - How do we reference the existing management log analytics workspace in custom assignments please?

### ISSUE THREAD

**Issue by danailedms** [Azure/terraform-azurerm-caf-enterprise-scale#255]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 0.15.0

**azure provider**: Unknown

**module**: 1.0.0

### Description

There appears to be no apparent way to reference the log analytics instance id as part of a policy assignment. Can we get clarity on this please?

Policy assignment stands as follows, copying from the definition for the inbuilt assignment policy_assignment_es_deploy_azactivity_log.tmpl.json...

{
  "name": "Deploy-LAA-Subs",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2019-09-01",
  "properties": {
    "description": "Allow Security Center to auto provision the Log Analytics agent on your subscriptions to monitor and collect security data using a custom workspace.",
    "displayName": "Enable Security Center's auto provisioning of the Log Analytics agent on your subscriptions with custom workspace.",
    "notScopes": [],
    "parameters": {
      "logAnalytics": {
        "metadata": {
          "description": "Select Log Analytics workspace from dropdown list. If this workspace is outside of the scope of the assignment you must manually grant 'Log Analytics Contributor' permissions (or similar) to the policy assignment's principal ID.",
          "displayName": "Log Analytics workspace",
          "strongType": "omsWorkspace"
        },
        "type": "String",
        "value": "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/${root_scope_id}-mgmt/providers/Microsoft.OperationalInsights/workspaces/${root_scope_id}-la"
      }
    },
    "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/8e7da0a5-0a0e-4bbc-bfc0-7773c018b616",
    "scope": "${current_scope_resource_id}",
    "enforcementMode": "Default"
  },
  "location": "${default_location}",
  "identity": {
    "type": "SystemAssigned"
  }

**Comment by jtracey93** [comment]
Hey @danailedms,

Thanks for raising this issue. 

They way to reference it today, providing you have not set custom names for the log analytics workspace via the advanced options, is the following string:

`/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/${root_scope_id}-mgmt/providers/Microsoft.OperationalInsights/workspaces/${root_scope_id}-la` 

But swap out the subscription ID with the correct subscription ID you have specified as the management subscription in the provider configuration as per https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Provider-Configuration

Hope that helps

Thanks

Jack

**Comment by krowlandson** [comment]
Both this issue, and #207 would both benefit from us providing a number of additional "out of the box" template files covering things like the Log Analytics workspace ID, along with other internally calculated values.

Will add this to the backlog for a near-future release.

In the meantime, the best fix is to simply provide the Log Analytics workspace ID as an input parameter on the Policy Assignment rather than relying on the templating to be able to correctly set this.

**Comment by krowlandson** [comment]
Thank you for your patience investigating this issue. I appreciate this can be a bit tricky to get right the first time.

Looking at the Gist, I think it would be useful to be aware of the following behaviours of the module:

- When we set “managed” values on a number of our policies, we are doing so by creating input parameters for the Policy Assignments based on their names and the scope at which they're being assigned. In the case of the `Deploy-Resource-Diag` Policy Assignment, this can be seen in the code here:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4c64874539456b3596fd3c6030d114693258bf04/modules/management/locals.tf#L219-L221
- If you replace the Policy Assignment template with your own version with the same name, you will be able to use these input parameters as originally intended, but are also limited to these being the only values you can input.
- If you create your own Policy Assignments (with new names), the module has no way of knowing to map these values to the input parameters, so you must provide them yourself.

In this particular scenario, you will need to provide the Policy Assignment with a valid Log Analytics workspace ID.

Because you are making these amendments to the default `es_root` archetype and at the `root` scope, you would need to add the following block of code to your module declaration:

```hcl
module "enterprise_scale" {

# existing code

  archetype_config_overrides = {
    root = {
      archetype_id   = "es_root"
      parameters     = {
        "Custom-Deploy-Res-Diag" = {
          logAnalytics = "" # <---- Enter your Log Analytics workspace ID here
        }
      }
      access_control = {}
    }
  }

}
```

This should ensure that the correct value gets assigned to your Policy Assignment.

Just to note, we are looking at options to make this easier (and more obvious to configure).

If you would like to better understand how this works under the hood, we do the following (looking primarily at the context of the `root` Management Group:

1. We create a default object defining the default archetype config for each of the default Management Groups:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4c64874539456b3596fd3c6030d114693258bf04/locals.management_groups.tf#L15-L19
2. Then we create a map of the customer provided overrides:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4c64874539456b3596fd3c6030d114693258bf04/locals.management_groups.tf#L86-L89
3. Which are then merged into a base configuration object:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4c64874539456b3596fd3c6030d114693258bf04/locals.management_groups.tf#L90-L93
4. As part of determining the archetype configuration for each Management Group (using the archetype sub-module), we merge the "managed" values set by the `connectivity`, `identity` and `management` sub-modules with the base configuration object from above:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4c64874539456b3596fd3c6030d114693258bf04/locals.management_groups.tf#L283-L301

Effectively, by providing a configuration block as suggested earlier, you are setting a custom input which takes priority on line `297` of the merge process above.

Hopefully this description helps you to fix your problem and better understand how this works 😄

**Comment by krowlandson** [comment]
Added to release:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/releases/tag/v1.1.2
