### ISSUE TITLE
Feature Request: Support privatelink / private dns zone for appserviceenvironment.net

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-caf-enterprise-scale#270]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

Would it not make sense to add support for app service environment in https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/e4019d8f8943cc341ba8fd13ba29c105d48031d1/modules/connectivity/variables.tf#L99 like for other services? This is maybe even more relevant for app service environments, as these are often used in order to be able to scale (as in ease) deployments of appfunctions into private vnets. 

**Additional context**

**Comment by krowlandson** [comment]
@davidkarlsen, thank you for logging this issue.

Azure Private Endpoint DNS configuration support within the module is based on the published [DNS zone configuration for Azure services](https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns#azure-services-dns-zone-configuration). The longer term goal of the module is to not only setup Private DNS zones for these services, but also to apply and configure corresponding Policy Assignments to ensure any services implemented with Private link are connected to the centralised DNS zone(s).

I don't believe we have a mismatch currently although you may need to map the "friendly name" from the variable to the actual underlying service using the following block of code within the module to see how they are related to DNS namespaces (we actually spent a fair amount of time discussing the best naming convention for these given how Terraform code "should" look):

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/e4019d8f8943cc341ba8fd13ba29c105d48031d1/modules/connectivity/locals.tf#L576-L627

Regarding app service environments, I don't believe these are explicitly supported for private link, which is why they are missing from this configuration.

To add the required `appserviceenvironment.net` DNS namespace, you can simply add this to your module configuration using the following:

```hcl
  configure_connectivity_resources= {
    settings = {
      hub_networks = [
        # Insert hub network configuration here
      ]
      vwan_hub_networks = [
        # Insert VWAN hub network configuration here
      ]
      ddos_protection_plan = {
        # Insert DDoS protection plan configuration here
      }
      dns = {
        enabled = true
        config = {
          location = ""
          enable_private_link_by_service = {
            # Define which private link DNS zones to enable here
          }
          private_link_locations                                 = []
          public_dns_zones                                       = [] # <-- This is where you add your own public DNS zones
          private_dns_zones                                      = [
            "appserviceenvironment.net"                               # <-- This is where you add your own private DNS zones
          ]
          enable_private_dns_zone_virtual_network_link_on_hubs   = true
          enable_private_dns_zone_virtual_network_link_on_spokes = true
        }
      }
    }
    location = null
    tags     = null
    advanced = null
  }
}
```

Please let me know whether this helps, or if I have misunderstood your question.

**Comment by davidkarlsen** [comment]
@krowlandson My assumptions here were wrong, thank you very much for a very clarifying answer (and also information on planned future changes). Much appreciated.

**Comment by krowlandson** [comment]
Great stuff... glad to be able to help!
