### ISSUE TITLE
Movement of subscription within child management group impossible

### ISSUE THREAD

**Issue by manfred0191** [Azure/terraform-azurerm-caf-enterprise-scale#303]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**: 1.1.3

### Description

**Describe the bug**

**Steps to Reproduce**

1. step 1
2. step 2
3. you get it...

**Screenshots**

**Additional context**

Hello,

I currently have a management group as a child group of the Tenant Root Group with several subscriptions (needed for the module) in it. I want to let the module build the enterprise scale set management group hierarchy from the scope of the child group with a service prinicpal that has permissions only on this child group and below, not on the Tenant Root Group.

Currently while deploying I get the error message like

`│ Error: unable to de-associate Subscription "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx" from Management Group "my-grp": managementgroups.SubscriptionsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Permission to write and delete on resources of type 'Microsoft.Authorization/roleAssignments' is required on the subscription or its ancestors." Details=[{"raw":"Subscription ID: '/subscriptions/xxxxx-xxxxx-xxxxx-xxxxx-xxxxx'"}]
`

Any idea how to solve this?

P.S.: From the Azure CLI it works, I can move a subscription to a created management group under my child group. That means that the permissions in general are definitely sufficient, but it seems like the module needs a permission on the Tenant Root Group, which this service principal must not have.

**Comment by manfred0191** [comment]
I think this is related to the following issues:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/223

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/24

https://github.com/hashicorp/terraform-provider-azurerm/issues/9833


The question is if this is the same issue and if there is already a solution to it

**Comment by krowlandson** [comment]
Hi @manfred0191... thank you for logging this issue.

I am going to assume that when you successfully perform these operations using Azure CLI, you are doing so with the same Service Principal that you use for the Terraform pipeline?

I have been speaking with my colleagues about this and we're all in agreement that this is likely to be a provider issue, rather than the module, but we need to validate something first.

Are you able to confirm whether you are also using Terraform (_outside of the module_) to manage the Management Group and Subscriptions that you reference above? Also, do you have any Tenant-level restrictions (_such as [requiring authorization](https://docs.microsoft.com/en-us/azure/governance/management-groups/how-to/protect-resource-hierarchy#setting---require-authorization)_) in relation to Management Group settings?

Typically, when moving a Subscription between Management Groups, Terraform will first `destroy` the original association and then `create` a new association. This means that the Subscription will move to [`default` Management Group](https://docs.microsoft.com/en-us/azure/governance/management-groups/how-to/protect-resource-hierarchy#setting---default-management-group). Assuming Terraform is doing this (_regardless of my questions above_), then you may run into the following issue with Terraform, that's not being observed with Azure CLI which is able to re-associate without this "double move":

> If the Owner role on the subscription is inherited from the current management group, your move targets are limited. You can only move the subscription to another management group where you have the Owner role. You can't move the subscription to a management group where you're only a contributor because you would lose ownership of the subscription. If you're directly assigned to the Owner role for the subscription, you can move it to any management group where you're a contributor.

**src**: [Moving management groups and subscriptions](https://docs.microsoft.com/en-us/azure/governance/management-groups/manage#moving-management-groups-and-subscriptions)

Are you able to set your custom `root` Management Group to be the [`default` Management Group](https://docs.microsoft.com/en-us/azure/governance/management-groups/how-to/protect-resource-hierarchy#setting---default-management-group) to see whether this resolves the problem?

Another possible solution might be to ensure that `Owner` permissions are explicitly set on the Subscriptions you want to move, assuming they are only getting this through inheritance from your custom `root` Management Group.

As a final thought, have you considered making your custom `root` Management Group **_the_** `root` Management Group for the module? Although not immediately obvious, you can do this by creating it with the correct values for `root_id` and `root_name` and then importing it into Terraform. Of course, it will also `destroy` this Management Group if you decide to completely re-deploy your environment in the future so please be aware of this.
Please let me know how you get on and if this requires further support.

**Comment by manfred0191** [comment]
Hi Kevin,
I think you can close this issue, because I simply set the variables not correctly: The variable `parent_root_id` was pointing to the tenant management group and as soon as I was changing it to the child group, the problem was gone. The only thing is I needed to establish another layer in between, so that the destruction of the environment results in putting the subscriptions back to where they came from. There is still another bug concerning the owner permissions of the subscriptions, but this has nothing to do with the model - it's a bug in Azure itself.

Anyway thanks for your help, which was highly appreciated

**Comment by krowlandson** [comment]
Thank you for confirming @manfred0191. Glad to hear you've managed to resolve the issue.

If you need further assistance, please let us know!

**Comment by manfred0191** [comment]
Hello,

can you please tell me how to define an individual name for a
resourcegroup in the Azure Terraform CAF Model?

To rename a management resource group I found out that I have to add in
the "advanced" section of settings_management.tf like

     advanced = {
       custom_settings_by_resource_type = {
         azurerm_resource_group = {
           management = {
             name = "rg-fits-test-mgmt"

but in the settings_connectivity.tf this doesn't work:

     advanced = {
       custom_settings_by_resource_type = {
         azurerm_resource_group = {
           connectivity = {
             name = "rg-fits-test-connectivity"


What do I have to set there to get an indidual name for the RG ??



--
Diese E-Mail wurde von AVG auf Viren geprüft.
http://www.avg.com
