### ISSUE TITLE
Seperate Operational logging from security logging

### ISSUE THREAD

**Issue by MarcelHeek** [Azure/terraform-azurerm-caf-enterprise-scale#316]
Hi,

In the current version (1.1.4)  of the module the management capability renders a single Log Analytics workspace. By using the "configure_management_resources" variable we can somehow steer the enablement of solutions and enable MDFC components.

However this all rolls up to one LA workspace which poses an issue when different teams need to access the Sentinel / LA workspace with separate duties like a SecOps team and a Platform Ops teams. There is no way to log everything to one workspace and shield the SecOps guys from accessing operation data and vice versa shield security data for the Platform Ops team.

Is there a way to achieve this ? So we can get two LA workspaces and separate operational logging from security logging somehow ?

**Comment by matt-FFFFFF** [comment]
Hi @MarcelHeek 

This module is an implementation of the ALZ conceptual architecture and therefore follows the reference implementation guidance for a single workspace here: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/management-platform#inventory-and-visibility-recommendations

Could you deploy another Log Analytics workspace outside of the module?

**Comment by MarcelHeek** [comment]
Hi @matt-FFFFFF 

Thanks for responding. I could deploy another LA workspace (not done yet) outside of the module scope, but what would be the underlying reason for deploying another workspace in the context of the modules management capability ? 

In regards to the link you mention it states exceptional reasons could exist to decide not to log everything to one workspace. I have such an exception at hand where our cloud platform operations team needs access to all operation data and our security operations team needs only access to the security data (sentinel / MDFC / security related records in LA workspace). This SecOps team is backed by an external party performing the role of security analyst and assist our SecOps teams. We do not want to expose all operational monitoring data to the SecOps team /external party and vice versa.

**Comment by matt-FFFFFF** [comment]
Hi @MarcelHeek,

Do you have a view on what you would like the module to provide? We can then log it as an enhancement and prioritize accordingly.

For example, are you asking for multiple Log Analytics workspaces, with policy set to log data to both?

If you could provide as much detail as possible then that will help. Thanks :)

**Comment by matt-FFFFFF** [comment]
Also @MarcelHeek,

Does the following help resource-contect access mode help with a centralized LA workspace?

* [Resource-context access mode](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/design-logs-deployment#access-mode)
* [Table level RBAC](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/manage-access#table-level-azure-rbac)

This way the application teams can have access to the logs for the resources they manage.

Also, the table level security can help restrict central teams access at a workspace level.

**Comment by matt-FFFFFF** [comment]
Hi @MarcelHeek,

Thanks for your detailed response!

After consideration we are not currently planning to implement this pattern in this module, however you are free to deploy the additional workspace using `azurerm_log_analytics_workspace` resources.

However before doing this I recommend reading the following article:
https://docs.microsoft.com/en-us/azure/sentinel/design-your-workspace-architecture#combining-your-soc-and-non-soc-data

If you do decide to deploy multiple workspaces, you can then use this module to create additional policy assignments to support sending data to both workspaces. See the wiki article on expanding built in archetypes: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions.

You would have to create an additional policy assignment file and then use the resource id of the new workspace as a parameter.

I will leave this open and mark it as an `enhancement` to gather feedback.

**Comment by MarcelHeek** [comment]
Hi @matt-FFFFFF,

once again, thanks for responding. How does this repo relate to the following : https://github.com/Azure/caf-terraform-landingzones-platform-starter

As I can see in this repo, the resource creation for management, identity resources is pulled out of the logic of the module and are created within their own config.  The config where the RG structure, ArcheType etc are defined work with YAML files which can be processed into tfvars files that use key referenced to the resources made in the "management" config. In the YAML files one is capable of entering a seperate law for ASC (should that not be MDFC ?), see screenshot of the YAML file

![image](https://user-images.githubusercontent.com/84451910/161748149-518d5c3e-cf00-405e-b9b9-fc8f4fdb4e08.png)

and the resulting tfvars file

![image](https://user-images.githubusercontent.com/84451910/161748350-db340945-e912-42de-b8a7-b0a7abc42c04.png)

Does this not solve my problem ?

**Comment by matt-FFFFFF** [comment]
Hi @MarcelHeek,

The repository you mention is part of a different project that consumes this module. It is an opinionated approach to Terraform on Azure that is not required to use this module, but may be beneficial to your organisation.

In terms of what you are looking at, these are policy parameters that are being set.

It is possible to override these using the [archetype_config_overrides](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-archetype_config_overrides) variable, where you can set a different LA workspace for the MSDFC policy.

That additional workspace must be deployed outside the scope of this module, however. This is true even of the caf-terraform-landingzones project you mention above.

**Comment by adhodgson1** [comment]
So its likely we will not deploy the management module of enterprise-scale for the following reasons:
- Our use case requires Log Analytics workspaces deployed to specific regions and we target diagnostic settings to log to the relevant region where the resource lives.
- We want to log specific diagnostic settings to the workspace only which is a strict security requirement. For example, there is a requirement to log firewall network traffic to storage accounts but log the metrics to Log Analytics as the network logs can be fairly busy.
- We would prefer to manage the diagnostic settings configuration with Terraform and not have a policy update these settings, this is mainly due to the reason above.
Just sending this as feedback.

**Comment by krowlandson** [comment]
Thank you for the feedback @adhodgson1 

I'm going to close this issue as we do not plan to update the module to address this due to it not being aligned to the ALZ recommendations, but I just wanted to respond to the points raised above in case anyone else is considering this.

- Whilst we recognise the desire for some organizations to have regional instances of Log Analytics workspaces, this is not recommended in our guidance due to the following:
    - Policy complexity (i.e. how do you ensure diagnostic logs are sent to correct regional LAW?)
    - Running queries across multiple LAW namespaces requires complex JOIN queries
    - Knowing which LAW do non-regional / global resources send logs to? What about Activity Log data from Subscriptions?
    - Additional complexity when integrating LAW with external solutions, such as SIEM and SOAR tooling
- Using LAW instances for specific logging scenarios such as SQL logs, network flow logs, etc. is a good idea, but we tend to treat these in the context of deployment stamps, similar to how you'd consider managing APM logging for application workloads. In this case, the network team are effectively treating network logs as their "application" logs, so they would be responsible for their own LAW instance(s) rather than using the central "platform" LAW instance.
- Managing the diagnostic settings configuration with Terraform is a common ask and we suggest setting the `enforcementMode` to false for the corresponding Policy Assignments to achieve this as it effectively converts the `DeployIfNotExists` action to `AuditIfNotExists`.
