### ISSUE TITLE
Feature Request Data management & Data Landing zones

### ISSUE THREAD

**Issue by JohanLander** [Azure/terraform-azurerm-caf-enterprise-scale#327]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add support for CAF Data management and analytics senario´s 

**Describe the solution you'd like**
I missing data management and data landing zones  in TF landing zones parts.  could you please add this to next version ? . 
ref :
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/

![image](https://user-images.githubusercontent.com/16382542/161779462-e6169b10-83d2-4948-9d5b-ba440c573e18.png)

**Comment by krowlandson** [comment]
Thank you for raising your issue @JohanLander.

I don't have an immediate answer for you on this as we will need to discuss this as a team. We don't currently have this option available for any of our `ALZ` implementation options as these are considered `solutions` which are compatible with ALZ rather than a part of ALZ itself.

Let me start a conversation internally, and we will come back to you soon.

**Comment by JohanLander** [comment]
I have had a dialog with cloud architect at Microsoft about this and they want it under platform branch .. just for you knowledge

**Comment by krowlandson** [comment]
hi @JohanLander... are you able to ask them to get hold of me internally so we can close the loop on this please?
