### ISSUE TITLE
How can I rename resources?

### ISSUE THREAD

**Issue by manfred0191** [Azure/terraform-azurerm-caf-enterprise-scale#332]
Hi,
I am looking for a possibility to give **all resources** deployed by the model a name by **my individual naming convention**.

To do this I wanted to start with the **resource groups.**

For the management resource group, I can add in my settings_management.tf 

```
locals {
  configure_management_resources = {
...
...
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          management = {
            name = "rg-fits-test-mgmt"
          }
        }
      }
    }
  }
}
```

and the resource group gets the name specified and no longer the "rootid-mgmt" which is otherwise given.

For the connectivity this doesn't work. If setting in the settings_connectivity.tf

```
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          connectivity = {
            name = "rg-fits-test-connectivity"
          }
...
```

the resource group gets the name "rootid-connectivity-location" as before.

What do I have to set in the settings_connectivity.tf under advanced so that the name is given like I want it to be for all resource groups deployed in the connectivity subscription??

**Comment by krowlandson** [comment]
Hi @manfred0191... great that you've got this working and you're on the right track.

Due to the extra Resource Groups needed for `connectivity`, they also include an additional `location` element to their `scope` when targeting each, as indicated by the following line of code:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/c773f614dfb409a67a11426c6ce77faedd132e14/modules/connectivity/locals.tf#L247

As such you need to use the following:

```hcl
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          connectivity = {
            westeurope = { # replace with the location you're using
              name = "rg-fits-test-connectivity"
            }
          }
...
```

Note that there are also multiple Resource Groups for different resource categories, as per the broader context of the local setting these:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/c773f614dfb409a67a11426c6ce77faedd132e14/modules/connectivity/locals.tf#L243-L264

Hope this helps?

**Comment by krowlandson** [comment]
Just going to cross-reference #292 as these requests are related.

**Comment by manfred0191** [comment]
You are perfect, but I guess you know that ;)

And now the final question: For the recource groups virtual_wan, dns and ddos, is it done accordingly and in the same advanced block?

Can you maybe give an example as of how to do it for all 4 RGs ??

**Comment by manfred0191** [comment]
Forget it, I got it:

```
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          connectivity = {
            (var.location) = {
              name = "rg-fits-test-connectivity"
            }
          },
          dns = {
            (var.location) = {
              name = "rg-fits-test-dns"
            }
          }
        }
      }
    }
  }
}
```

Anyway thanks so much for your help !!!

**Comment by krowlandson** [comment]
That's the one 😄

**Comment by krowlandson** [comment]
Same basic structure but you have to reference `expressroute` or `vpn` instead of `connectivity` within the block, as per:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/c773f614dfb409a67a11426c6ce77faedd132e14/modules/connectivity/locals.tf#L441

and

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/c773f614dfb409a67a11426c6ce77faedd132e14/modules/connectivity/locals.tf#L524

resulting in:

```hcl
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_virtual_network_gateway = {
          expressroute = {
            (var.location) = {
              name = "expressroute-gateway"
            }
          },
          vpn = {
            (var.location) = {
              name = "vpn-gateway"
            }
          }
        }
      }
    }
  }
}
```

**Comment by manfred0191** [comment]
Yep, again that worked - as your advices always do ;)

But for the pip, there is no way of renaming it, right?

**Comment by manfred0191** [comment]
Thanks Kevin, so I will let @mbilalamjad open the request.

Yes, I agree, it also surpises me that the suggested naming convention for Azure resources has not been taken into consideration. But it is like it is. If one can change it, everything is fine.

**Comment by krowlandson** [comment]
Made progress on PIP renaming in the code for our next release:

![image](https://user-images.githubusercontent.com/12268562/163123245-06618f29-5b34-475b-b1ca-0be534c7a880.png)

**Comment by krowlandson** [comment]
@manfred0191 - **IMPORTANT** Please take note of the PR description on #331 so you're aware of the breaking changes before upgrading when this code is merged and released! We will do our best to document this clearly, but want to raise additional awareness.

**Comment by manfred0191** [comment]
Sounds great. I already told you that you're the best. Nothing to add to that.

**Comment by krowlandson** [comment]
Release `v2.0.0` is now live, with detailed instructions regarding the upgrade also available.

Please see the release notes for more information:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/releases/tag/v2.0.0

I will close this issue as I believe we've dealt with it, but please feel free to open a new one if you require further assistance.
