### ISSUE TITLE
Feature Request: Log Analytic instances in multiple regions 

### ISSUE THREAD

**Issue by giovannifl-wpp** [Azure/terraform-azurerm-caf-enterprise-scale#363]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=description>Description </h3>
<p><strong>Is your feature request related to a problem?</strong>
I have the requirement to use multiple Azure regions ( i.e. UK South and UK West) and they may be deployed under the same MG structure. This is means that in the Management Zone at least two Log Analytic instances should be deployed ( as per Microsoft Best Practices), one for UK West and one for UK South. Currently ESLZ (Enterprise Scale Landing Zone) approach, forces all Azure resources, deployed in ANY regions to send their logs into the &quot;only&quot; Log Analytic that exists in the Management Zone. </p>
<p><strong>Describe the solution you'd like</strong>
Extend Management Zone to support the concept of &quot;Regions&quot;: a user can provide a list of Azure regions (as a parameter) for the Management Zone and ESLZ Terraform module will take care of: </p>
<ul>
<li>Deploy a Log Analytic instance in each region provide by the user </li>
<li>Configure Azure policy so that Azure resources will send their logs to the &quot;regional&quot; Log Analytic ( A custom policy will be required for this ) </li>
</ul>
<p><strong>Additional context</strong> </p>

**Comment by krowlandson** [comment]
Thank you for logging this request.

Because this module is designed around the recommended ALZ architecture and design patterns, we only support a central Log Analytics workspace. However you can technically deploy only the management resources by setting `deploy_core_landing_zones = false` along with `deploy_management_resources = true` and using `default_location` (or the location settings within `configure_management_resources`) to target the desired location.

This would give you a consistent approach for deployment, and you could even standardise the `configure_management_resources` input when inheriting location from the `default_location` input variable.

However, as you rightly identify you would need to develop and deploy custom policies to ensure logs of each type are sent to the desired target Log Analytics workspace.

Another reason beyond our ALZ recommendations as to why we haven't developed this as a feature is because there are also variations on how this can be implemented depending on how an organisation operates. Some go for a Log Analytics workspace per location, whilst others align to larger geographical regions such as Americas, EMEA, and APAC. These variations would each require different solutions.

We also differentiate between logs for the platform (centralised) and then have guidance which allows for dedicated Log Analytics workspace(s) per application or application stack for APM. The former is what we're concerned by with ALZ, whilst the latter is operated by the individual application teams based on their requirements.

Happy to further consider and discuss your scenario, but hope this additional context helps.

**Comment by matt-FFFFFF** [comment]
Hi @giovannifl-wpp 

Thank you for your feedback request.

This module is an implementation of the ALZ conceptual architecture, and the log analytics (Azure monitor logs) workspace recommendation is to have a single workspace.

> Logging centralization drives reports about change management, service health, configuration, and most other aspects of IT operations. Focusing on a centralized workspace model reduces administrative effort and the chances for gaps in observability.

https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/landing-zone/design-area/management-platform#inventory-and-visibility-recommendations

You are able to deploy multiple workspaces outside the context of this module. You may wish to consider the effect of this on the DeployIfNotExists policies that are used, adding a customization for resource location.

You can use multiple instances of this module to deploy management resources to multiple locations should this be of use.

**Comment by krowlandson** [comment]
- Linking this issue to #392 as this will make it easier to understand how to implement just the Management resources at different scopes
- Worth noting that at this point there is no intention of updating the policies needed for this scenario as it doesn't align to the ALZ recommended approach of a centralized Log Analytics workspace

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by AlexcFrench** [comment]
Thank you very much for the feedback and explanation. We'll investigate further.

**Comment by krowlandson** [comment]
Trigger ADO Sync

**Comment by matt-FFFFFF** [comment]
We are leaving this open for tracking and are discussing all up ALZ architecture for this request
