### ISSUE TITLE
Unable to manage Azure Firewall following external changes 

### ISSUE THREAD

**Issue by tpatrizio** [Azure/terraform-azurerm-caf-enterprise-scale#385]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.1.9

**azure provider**: v3.7.0

**module**:  2.0.1

### Description

**Describe the bug**

I've successfully deployed the Azure firewall by enabling it in the settings.connectivity.tf, but after stopping and starting it from the cloud shell:

```
# Stop an existing firewall

$azfw = Get-AzFirewall -Name "FW Name" -ResourceGroupName "RG Name"
$azfw.Deallocate()
Set-AzFirewall -AzureFirewall $azfw

# Start the firewall

$azfw = Get-AzFirewall -Name "FW Name" -ResourceGroupName "RG Name"
$vnet = Get-AzVirtualNetwork -ResourceGroupName "RG Name" -Name "VNet Name"
$publicip1 = Get-AzPublicIpAddress -Name "Public IP1 Name" -ResourceGroupName "RG Name"
$publicip2 = Get-AzPublicIpAddress -Name "Public IP2 Name" -ResourceGroupName "RG Name"
$azfw.Allocate($vnet,@($publicip1,$publicip2))

Set-AzFirewall -AzureFirewall $azfw

```
I'm no longer able to apply changes to the enterprise scale configuration, even if it doesn't relate to the firewall. The apply phase ends with the following error:

```
Error: A resource with the ID "/subscriptions/<my-subscription-id>/resourceGroups/<my-connectivity-rg>/providers/Microsoft.Network/azureFirewalls/<my-azure-firewall>" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_firewall" for more information.
```
I'. also tryed to import the resource into the state

```
terraform import module.enterprise_scale.azurerm_firewall.connectivity /subscriptions/<my-subscription-id>/resourceGroups/<my-connectivity-rg>/providers/Microsoft.Network/azureFirewalls/<my-azure-firewall>
```
the command completes successfully but applying the plan fails with the same error.

**Steps to Reproduce**

1. deploy Azure firewall with enterprise_scale module;
2. stop and start it as documented [here](https://docs.microsoft.com/en-us/azure/firewall/firewall-faq)
3. change something in the ESLZ configuration (eg. apply an additional policy set to some management group
4. apply the cnages
5. you get it...

**Screenshots**

**Additional context**

**Comment by krowlandson** [comment]
@tpatrizio, thank you for your question

I don't believe this is a module issue, as it sounds like the firewall resource is missing from the Terraform state. This usually indicates that an issue occurred during a previous `terraform apply`. For this particular resource type, it can often be due to a timeout during creation where Terraform returns an error despite the resource being successfully created in the background.

You can check your Terraform state using the command `terraform state list` to confirm that this resource is definitely missing.

To run the import, please also take note of the resource naming convention used within the module. As all resources are created within a `for_each` loop, they must also be referenced by `key`. The `key` should be the same as the Resource ID of the resource being created. So for the resource you mention, the import command would be:

```shell
terraform import 'module.enterprise_scale.azurerm_firewall.connectivity[\"/subscriptions/<my-subscription-id>/resourceGroups/<my-connectivity-rg>/providers/Microsoft.Network/azureFirewalls/<my-azure-firewall>\"]' /subscriptions/<my-subscription-id>/resourceGroups/<my-connectivity-rg>/providers/Microsoft.Network/azureFirewalls/<my-azure-firewall>
```

Please also take care around the quoting and escaping around quotes in this command. The above example should work in a `PowerShell` environment but may need updating if running in `bash`.

Hopefully this helps, but please let me know if you need any further assistance.
