### ISSUE TITLE
Deploy Core, Management, Connectivity, Identity Resources to different TFC workspace (TF state files)

### ISSUE THREAD

**Issue by lintaonz** [Azure/terraform-azurerm-caf-enterprise-scale#391]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

Currently, if I switch the Management and Connectivity modules on, all resources will deploy to a single TFC workspace / TF state file.  If I add more custom landing zones, the single TF state file grows bigger and bigger. This makes the state file hard to maintain and easy for broken. 

**Describe the solution you'd like**

Can we define TF remote backend per module? So that I have different TFC workspaces (TF state files) for the four modules and the landing zones.

**Additional context**

**Comment by krowlandson** [comment]
Thank you for this question @lintaonz.

The basic design principle of the module allows you to sub-divide your implementation in exactly the way you are asking, allowing deployment of the following groups of resources to be deployed across multiple TFC workspaces (TF state files):

- Core resources (Management Groups with associated policies and IAM)
- Connectivity resources
- Management resources

These can even be sub-divided into multiple instances of the above, but as you might expect, this further increases complexity with diminishing benefit.

We actually do this partially within the [test framework modules](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/tests/modules), so the basic code structure you need to achieve this is partially available there. There is also documentation in our Wiki explaining how to split your core resources across multiple module declarations [using module nesting](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Using-Module-Nesting) but we should probably add explicit guidance covering this scenario in full.

To get you started, if you look at the [test framework modules](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/tests/modules) you will notice that we abstracted all of the configuration settings into a dedicated [settings module](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/tests/modules/settings), and moved the [custom lib folder](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/tests/modules/test_lib) up a level too. This allows the same inputs to be cross-referenced by each of the root modules used for resource deployments. This ensures each test module has consistent settings, and the same principle can be applied to your scenario.

The [test 003 module](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/tests/modules/test_003_add_mgmt_conn) is probably most similar to what you're looking for. If you look at the structure within [main.tf](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/tests/modules/test_003_add_mgmt_conn/main.tf), you will see we have multiple declarations of the module being called to deploy the following:

- [test_core](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/c6c585716d464b16bbe659632c2c0305f7c32021/tests/modules/test_003_add_mgmt_conn/main.tf#L1-L48) to build the base Management Group hierarchy
- [test_nested_core](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/c6c585716d464b16bbe659632c2c0305f7c32021/tests/modules/test_003_add_mgmt_conn/main.tf#L50-L84) to extend the Management Group hierarchy
- [test_management](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/c6c585716d464b16bbe659632c2c0305f7c32021/tests/modules/test_003_add_mgmt_conn/main.tf#L86-L115) to add the Management resources
- [test_connectivity](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/c6c585716d464b16bbe659632c2c0305f7c32021/tests/modules/test_003_add_mgmt_conn/main.tf#L117-L146) to add the Connectivity resources

As long as you do the following across each module declaration, you should be able to take each of these module declarations and move them into different root modules, allowing you to achieve your desired outcome:

- Use consistent values for `providers = {}` across all
- Use consistent values for `configure_*****_resources` input variables across all
- Use consistent values for `subscription_id_*****` input variables across all
- Toggle which resources are deployed using the `deploy_*****` input variables on each

If you look at how we did this using the [settings module](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/tests/modules/settings), you should be able to replicate this in a way which works across your multiple root modules.

TFC may make this a little trickier due to the way it works with initiating a root module. In my testing, TFC won't have access to folders which aren't directly under the root module path. You may get the following error (or similar):

```shell
╷
│ Error: Unreadable module directory
│ 
│ Unable to evaluate directory symlink: lstat ../alz_settings: no such file
│ or directory
╵
```

I don't have a specific solution to this, but I suspect there are multiple options using something like `symlinks` or `git submodules` to ensure the "external" folders are available within TFC, or you can simply store these values in TFC using [Variable sets](https://www.terraform.io/cloud-docs/workspaces/variables/managing-variables#variable-sets) which can be mapped to each workspace. The approach you settle on will depend on what's supported by TFC, and what your requirements are around having configuration settings stored in Version Control, vs. TFC.

Hope this helps, but please let me know if you require further guidance on this.

**Comment by lintaonz** [comment]
Hi @krowlandson,

Thank you for your great answer. I think I can figure it out based on the [test 003 module](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/tests/modules/test_003_add_mgmt_conn).

For the TFC error, I can use [Terraform Working Directory](https://www.terraform.io/cloud-docs/workspaces/settings#terraform-working-directory) to solve it. 

Yes, it would be great if you can add an example in the wiki in the future.
