### ISSUE TITLE
Feature Request -  Custom Setting Support for vnet peerings

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-caf-enterprise-scale#397]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add custom_settings support for Virtual Network Peerings

I'd like the ability to configure the names of my Vnet peerings to allow me to import them to state. Removing the need to destroy/recreate

    advanced = {
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          connectivity = {
            uksouth = {
              name = "vnpeer-uks-hub"
            }
          }
        }

**Comment by krowlandson** [comment]
Thank you for raising this @birdnathan and I can fully appreciate why you would want to do this.

My initial thoughts were that this is a tricky one, which is why we didn't offer it already.

Having looked at it again, the uniqueness of the peering name and resource ID is determined by a combination of the Resource Group it's created in (unique to a specific hub location) and the `uuidv5()` output of the spoke Virtual Network Resource ID (unique to a specific spoke within that hub).

This means we should be able to implement something like the following:

```terraform
advanced = {
  custom_settings_by_resource_type = {
    azurerm_virtual_network_peering = {
      connectivity = {
        location = {                     # replace `location` with the location of the hub_network
          "spoke_network_resource_id" = {  # replace `spoke_network_resource_id` with the Resource ID of the spoke network
            name = "vnpeer-uks-hub"
          }
        }
      }
    }
  }
}
```

> **NOTE:** You will probably need to double-quote the `spoke_network_resource_id` value due to its format

Does this sound like a fair approach?

**Comment by birdnathan** [comment]
> 

This approach seems logical to me @krowlandson. Thanks for looking into this

**Comment by krowlandson** [comment]
Great, let me get this on the backlog and prioritized... but please also feel free to contribute via a PR if you like? Happy to provide a few pointers on where the updates are needed if that helps?

**Comment by birdnathan** [comment]
> Great, let me get this on the backlog and prioritized... but please also feel free to contribute via a PR if you like? Happy to provide a few pointers on where the updates are needed if that helps?

Yeah id need some pointers on this, first time for everything though😊
