### ISSUE TITLE
Follow Azure naming conventions

### ISSUE THREAD

**Issue by nwmcsween** [Azure/terraform-azurerm-caf-enterprise-scale#446]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

Recommended naming conventions can be found: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations.

#### Describe the solution you'd like

Provide prefix/suffix options to follow naming conventions.

Tried to dig into how names are assigned but it seems a bit complicated to suffix things according to the Azure naming conventions.

**Comment by krowlandson** [comment]
Hi @nwmcsween ... thank you for logging this.

The CAF naming conventions are only there as guidance rather than being an explicit recommendation, however we are already discussing the option to improve flexibility around resource naming within the module, including an option to automatically apply names which follow the CAF naming conventions you mention.

I'm going to close this issue as a duplicate, but going to link to #292 as further evidence to prioritise this work.

In the meantime, if you need to update the naming to a specific pattern all resources created by the module can be renamed using the `advanced` inputs under management and connectivity settings. We do not document this as we expect to enable this using `optional()` types in a future release. Please let me know if you require further guidance on this.

Thank you

**Comment by krowlandson** [comment]
Trigger ADO Sync
