### ISSUE TITLE
Error assigning custom Azure policy to Archetype

### ISSUE THREAD

**Issue by john-nicholls-development** [Azure/terraform-azurerm-caf-enterprise-scale#45]
When attempting to create and assign a custom Azure Policy to an Archetype we are getting the following error:
```
Error: reading Policy Definition "Tag-Enforcement-Policy": policy.DefinitionsClient#GetBuiltIn: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicyDefinitionNotFound" Message="The policy definition 'Tag-Enforcement-Policy' could not be found."

  on .terraform/modules/enterprise_scale/locals.policy_assignments.tf line 141, in data "azurerm_policy_definition" "external_lookup":
 141: data "azurerm_policy_definition" "external_lookup" {
```
 
 Our belief is that the module is only checking for existing Azure Policies and is not checking for the custom policies that can be created as part of running this module. We have attempted to copy the example code located in the code base at `modules/archetypes/lib/policy_definitions/policy_definition_es_deny_appgw_without_waf.json` and `modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_appgw_without_waf.tmpl.json`

Our custom policy in `lib/policy_definitions/policy_definition_require_tags.json` contains:
```
{
  "name": "Tag-Enforcement-Policy",
  "type": "Microsoft.Authorization/policyDefinitions",
  "apiVersion": "2019-09-01",
  "properties": {
    "displayName": "Require a tag on resources",
    "policyType": "Custom",
    "mode": "Indexed",
    "description": "Enforces existence of a tag. Does not apply to resource groups.",
    "metadata": {
      "category": "Tags",
      "createdBy": "b769b5da-f41d-4ca2-a1ad-d16a67f9f7ba",
      "createdOn": "2020-11-05T21:45:23.6465795Z",
      "updatedBy": null,
      "updatedOn": null
    },
    "parameters": {
      "tagName": {
        "type": "String",
        "metadata": {
          "displayName": "Tag Name",
          "description": "Name of the tag, such as 'environment'"
        }
      }
    },
    "policyRule": {
      "if": {
        "field": "[concat('tags[', parameters('tagName'), ']')]",
        "exists": "false"
      },
      "then": {
        "effect": "deny"
      }
    }
  }
}
```

Our Policy Assignment in `lib/policy_assignments/policy_assignment_require_tags.json` contains:
```
{
  "name": "Tag-Enforcement",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2019-09-01",
  "properties": {
    "description": "Enforces existence of a tag. Does not apply to resource groups.",
    "displayName": "Tag-Enforcement",
    "notScopes": [],
    "parameters": {
      "tagName": {
        "value": "name"
      }
    },
    "policyDefinitionId": "${root_scope_resource_id}/providers/Microsoft.Authorization/policyDefinitions/Tag-Enforcement-Policy",
    "scope": "${current_scope_resource_id}"
  },
  "location": "${default_location}",
  "identity": {
    "type": "SystemAssigned"
  }
}
```

**Comment by krowlandson** [comment]
Hi @john-nicholls-development... thank you for your Issue.

To ensure we cover the situation you mention, the logic within the module will only perform a lookup against Azure for Policy Definitions which it doesn't find within the scope of the module. Otherwise it is already aware of definitions it is due to apply.

We do have a small "bug/feature" whereby the Policy Definition logic actually maps to the `properties.displayName` field instead of `name`. This is already fixed in our `main` branch as part of  #44, but this is yet to be released via TF Registry. For now you need both of these properties to match. In your case these would need to both be set to `Tag-Enforcement-Policy`.

As a quick heads-up... #44 includes a full refresh of the built-in policies which will bring the TF module up to date and in sync with the foundation policies from [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale). This update includes removing the `ES-` prefix from the policy names, but also results in a number of other policy name changes. Please be aware of this before upgrading from `v0.0.8` once the next release is available as you will need to update any custom archetypes included in your library. This will also result in a fairly significant re-deployment of most policies deployed by the module.

I'm also working to improve the documentation around customisation and extension of the module, including a guide to upgrading from `v0.0.8` to `v0.1.0` so please keep an eye out for this.

**Comment by krowlandson** [comment]
Further to my previous comment, please refer to this draft documentation regarding some of the big changes coming up in the next release:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Upgrade-from-v0.0.8-to-v0.1.0

**Comment by john-nicholls-development** [comment]
Thanks @krowlandson, we've got it working now

**Comment by krowlandson** [comment]
That's great, thank you for confirming @john-nicholls-development.

I'm sure you've already seen, but v0.1.0 has also been released now too.
