### ISSUE TITLE
Bug Report  azure_firewall duplication in variables 

### ISSUE THREAD

**Issue by frankscalzo** [Azure/terraform-azurerm-caf-enterprise-scale#452]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: </p>
<p><strong>azure provider</strong>: </p>
<p><strong>module</strong>: </p>
<h3 id=description>Description </h3>
<h4 id=describethebug>Describe the bug </h4>
<p>as im looking i see 2 spots in variables.tf for  azure_firewall </p>
<p>lines 483 and 529 </p>
<p>when i put true on both i see the one at 483 creates the Firewall with a private ip as and has the associated subnets  but 529 only creates the fw without any real association and in network watcher you can not even see it </p>
<p>can i understand the differences between the 2 </p>
<p>sorry i have tried to review documents ad i cant seem to find anything </p>
<h4 id=stepstoreproduce>Steps to Reproduce </h4>
<ol>
<li>step 1 </li>
<li>step 2 </li>
<li>you get it… </li>
</ol>
<h4 id=screenshots>Screenshots </h4>
<h4 id=additionalcontext>Additional context </h4>

**Comment by jtracey93** [comment]
Hi @frankscalzo,

Are you consuming the module from the registry, rather than cloning it and trying to use it?

If so, please review these Wiki docs on how to use the connectivity module, which is where the firewall is deployed/managed from: 

- https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources
- https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings
- https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources

Let us know if these help or not and if you need anything further 

Thanks

Jack
