### ISSUE TITLE
Unable to reference the Hub network created in settings.connectivity.tf

### ISSUE THREAD

**Issue by jenka13all** [Azure/terraform-azurerm-caf-enterprise-scale#457]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: 1.2.5 </p>
<p><strong>azure provider</strong>: ? </p>
<p><strong>module</strong>: settings.connectivity.tf </p>
<h3 id=description>Description </h3>
<h4 id=describethebug>Describe the bug </h4>
<p>We set &quot;enabled&quot; to true in settings.connectivity.tf (locals.configure<em>connectivity</em>resources.settings.hub<em>networks), which leads to a virtual network being created in our Connectivity subscription. We want to create a spoke network in a different subscription and peer it to the hub network. This does not work by just creating the spoke network in Terraform and putting its id in the &quot;spoke</em>virtual<em>network</em>resource<em>ids&quot; list of the hub</em>networks object, because the hub and the spoke are in different subscriptions. </p>
<p>So we are setting up the transitive peering from hub to spoke and spoke to hub in Terraform, which fails at the point where we need to reference the azurerm<em>virtutal</em>network for the hub network. How do we reference this? I can hardcode the hub networks' resource group name and network id, but how do I reference the resource required in the following block of code? </p>
<pre><code>resource &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;azurerm_virtual_network_peering&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;spoke_to_hub_peer&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; {
    provider                  = azurerm.kiss
    name                      = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;kiss-spoke-to-hub-peer&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
    resource_group_name       = azurerm_resource_group.itzb_kiss_rg.name
    virtual_network_name      = azurerm_virtual_network.spoke_vnet_kiss.name
    remote_virtual_network_id = var.hub_vnet_id # azurerm_virtual_network.hub-vnet.id
    allow_virtual_network_access = true
    allow_forwarded_traffic = true
    allow_gateway_transit   = false
    use_remote_gateways     = false
    depends_on = [
      azurerm_virtual_network.spoke_vnet_kiss, 
      local.configure_connectivity_resources.settings.hub_networks[0]
    ]
}
</code></pre>
<p>The error it returns is: References in depends_on must be to a whole object (resource, etc), not to an attribute of an object.
The same error occurs with the following values. </p>
<ul>
<li>local.configure<em>connectivity</em>resources.settings.hub_networks </li>
<li>azurerm<em>virtual</em>network.connectivity.itzb-hub-germanywestcentral, # same error </li>
</ul>
<h4 id=stepstoreproduce>Steps to Reproduce </h4>
<ol>
<li>Enable a hub network in settings.connectivity.tf </li>
<li>Create a virtual network in Terraform in a different subscription as the hub network </li>
<li>Try to peer the hub network to the spoke network or spoke network to hub network </li>
</ol>
<h4 id=screenshots>Screenshots </h4>
<h4 id=additionalcontext>Additional context </h4>

**Comment by krowlandson** [comment]
Hi @jenka13all ... thank you for logging this.

As you've already identified, there are some challenges around this due to the way Terraform works (and the way we constructed the data model in the module) which result in this behaviour. This means that you need to provide the input values for `spoke_virtual_network_resource_ids` as string literal values so Terraform can determine how many resources to create at `apply`.

Also due to the limitation you identified around provider configuration for creating resources across Subscriptions, we are only able to create `outbound` peerings from the hub-to-spoke. The spoke-to-hub peering must be handled outside of this module.

We will be working on some reference implementations covering this in the (hopefully) near future, but in the meantime we suggest the following options:

1. Use our [lz-vending module](https://registry.terraform.io/modules/Azure/lz-vending/azurerm/latest) which abstracts this whole process from this module and uses the new [azapi provider](https://registry.terraform.io/providers/Azure/azapi/latest/docs) to overcome the Subscription authorization issue
2. Build your own logic to do this, using [dependency inversion](https://www.terraform.io/language/modules/develop/composition#dependency-inversion) to lookup the hub network using Terraform data resources, either for both peering directions, or for the inbound only

When we first published this capability, we found a number of customers were using the module to create the outbound peerings for "approved spoke networks" and then letting the landing zone owners create the inbound peerings independently, so you may also consider this approach.

Hope this helps?

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Awesome, thank you for confirming @jenka13all

**Comment by krowlandson** [comment]
Trigger ADO Sync
