### ISSUE TITLE
Bug Report[Question]: The custom role definition name gets prefix added

### ISSUE THREAD

**Issue by nonamecoder2002** [Azure/terraform-azurerm-caf-enterprise-scale#485]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.2.9

**azure provider**: 2.3.1

**module**: Azure/caf-enterprise-scale/azurerm

### Description

The custom role definition name gets prefix added. When adding the custom role def. to the `"role_definitions": []` in the `archetype_definition_root.json `, the `scope_id` prefix gets added to the role name.

**For instance:**
Role name in the def **.json** file: `rolename-1 `
When running terraform plan its: ` [LZ-ENV] rolename-1`

### Question:
I"ve done some research and found out that this behavior is caused in: `.terraform\modules\enterprise_scale\modules\archetypes\locals.role_definitions.tf` line 98:

` role_definition_name = "[${basename(upper(local.scope_id))}] ${local.archetype_role_definitions_map[local.convert_role_definition_name_to_id[role]].properties.roleName}"
`
**My question is How can I disable this behavior/override it?** So, I get no prefix added to the custom role name=)

#### Steps to Reproduce

1. Create custom role .json file
2. Add the custom role name to the `"role_definitions": []` in the `archetype_definition_root.json `
3. The `scope_id` prefix gets added to the role name: `rolename-1` ==> ` [LZ-ENV] rolename-1`

**Comment by krowlandson** [comment]
Thank you for raising this @nonamecoder2002 

This is by design to ensure unique naming for all Role Definitions created by the module, avoiding failures due to naming conflicts. Role Definition names must be unique at the Tenant scope, hence this requirement.

This format ensures unique names are generated when following our [canary](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/enterprise-scale/testing-approach) guidance (i.e. deploying multiple times within the same tenant) or when creating the same Role Definition at different scopes within the management group hierarchy for testing/validation.

If you still want to set a custom name for your Role Definition(s), please create them outside the module using the [azurerm_role_definition](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_definition) resource type.

I will discuss this with the team to see whether we want to add this feature, however this is the first time we have been asked for this so it will need to be triaged and prioritised if considered.

Hope this helps?

**Comment by nonamecoder2002** [comment]
Much thanks for your response @krowlandson 

Yeah, I think this helps;)

**Comment by krowlandson** [comment]
Trigger ADO Sync
