### ISSUE TITLE
Issue when upgrading from version 1.1.4 to 2.0.0 - Invalid Index

### ISSUE THREAD

**Issue by cmohams9** [Azure/terraform-azurerm-caf-enterprise-scale#490]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.0.9

**azure provider**: 3.27.0

**module**: 1.1.4

#### Describe the bug

I am trying to upgrade the module version to 2.0.0 and I use an Azure DevOps pipeline to execute the build. Terraform Plan step returns the following errors

╷
│ Error: Invalid index
│ 
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.role_definitions.tf line 94, in locals:
│   94:       resource_id          = "${local.provider_path.role_definition}${local.convert_role_definition_name_to_id[role]}"
│     ├────────────────
│     │ local.convert_role_definition_name_to_id is object with 7 attributes
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.role_definitions.tf line 97, in locals:
│   97:       template             = local.archetype_role_definitions_map[local.convert_role_definition_name_to_id[role]]
│     ├────────────────
│     │ local.convert_role_definition_name_to_id is object with 7 attributes
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.role_definitions.tf line 98, in locals:
│   98:       role_definition_name = "[${basename(upper(local.scope_id))}] ${local.archetype_role_definitions_map[local.convert_role_definition_name_to_id[role]].properties.roleName}"
│     ├────────────────
│     │ local.convert_role_definition_name_to_id is object with 7 attributes
│ 
│ The given key does not identify an element in this collection value.

#### Steps to Reproduce

1. Change the CAF Module version from 1.1.4 to 2.0.0
2. Update Azure RM and other provider versions to 2.0.0 dependency - >https://registry.terraform.io/modules/Azure/caf-enterprise-scale/azurerm/2.0.0?tab=dependencies
3. Run Build Pipeline to execute the following steps - Download Secrets, Terraform Install, Initialize Terraform, Terraform Validate and Terraform Plan. The plan returns the above error.

#### Screenshots

<img width="851" alt="image" src="https://user-images.githubusercontent.com/92427489/195915518-98350632-a7e7-43ba-a8ab-95a7e8cbfe5d.png">

**Comment by krowlandson** [comment]
@cmohams9 ... this part of the code is used to map Role Definition names to resource IDs. The usual reason for this error would be due to an entry in the `role_definitions` list referenced in an archetype definition missing from the lib. As we include all of our OOTB templates in the lib folder within the module, this would suggest that you have a reference to a custom Role Definition which is missing from your custom lib folder.

Assuming you haven't changed anything related to roles from the previous version, this may be a false error. We have observed that Terraform will sometimes throw an error like this when another issue in the configuration has occurred which prevents completion of all processes, resulting in a cascade of errors like this.

Please double-check whether you have addressed all of the points mentioned in the [upgrade guide](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Upgrade-from-v1.1.4-to-v2.0.0). If that still doesn't address the issue we will need to take a look at your code base to troubleshoot.

Please also check whether you have any other resources defined in your root module (not deployed by our module) to ensure these are also correctly configured for the latest required Terraform and provider versions.

**Comment by krowlandson** [comment]
Following offline conversations, please validate that all referenced Role Definitions (from the archetypes, but also those which are already in the Terraform state) have corresponding Role Definition templates included within either the built-in or your own custom `lib` folder.

If you require further support on this, please let me know 👍🏻

**Comment by cmohams9** [comment]
Thanks, @krowlandson for helping with this. The Issue was fixed by replacing the custom role definitions with the ones from the archetypes of the upgraded module.

**Comment by krowlandson** [comment]
Closing as resolved
