### ISSUE TITLE
Feature Request - vwan hub connections - Internet_Security_Enabled should be a variable.

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-caf-enterprise-scale#491]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I've been deploying vwan hubs with this module however i've found that the "Internet_Security_Enabled" parameter for hub connections is hardcoded to false within the connectivity/locals.tf file. If I use the module to create these vnet connections and then afterwards set the global firewall security settings (which sets the value on the connection to true) subsequent deployments will change this back.

```hcl
# Configuration settings for resource type:
#  - azurerm_virtual_hub_connection
locals {
  azurerm_virtual_hub_connection = flatten(
    [
      for location, virtual_hub_config in local.virtual_hubs_by_location :
      [
        for spoke_resource_id in virtual_hub_config.config.spoke_virtual_network_resource_ids :
        {
          # Resource logic attributes
          resource_id       = "${local.virtual_hub_resource_id[location]}/hubVirtualNetworkConnections/peering-${uuidv5("url", spoke_resource_id)}"
          managed_by_module = local.deploy_virtual_hub_connection[location]
          # Resource definition attributes
          name                      = "peering-${uuidv5("url", spoke_resource_id)}"
          virtual_hub_id            = local.virtual_hub_resource_id[location]
          remote_virtual_network_id = spoke_resource_id
          # Optional definition attributes
          internet_security_enabled = false
          routing                   = local.empty_list
        }
      ]
    ]
  )
}
```

#### Describe the solution you'd like

Can we parametrise this value? In the example i have been testing I would be happy to set the same value on all spoke virtual networks but I guess there could be a use case where you want to set a different boolean value per connected virtual network so may need to expand the logic around the spoke_virtual_network_resource_ids array and how this setting is ultimately applied to each.

**Comment by krowlandson** [comment]
hi @birdnathan ... thank you for raising this. We will investigate the options for this and come back to you soon 😄

**Comment by KeynesLee** [comment]
Hi 

May I know, before the parameter **Internet_Security_Enabled** becomes a variable, how could we enable this feature in a deployed CAF virtual wan ?  I mean, route all spoke vnets Internet Traffic to Azure Firewall.

**Comment by krowlandson** [comment]
@KeynesLee unfortunately this is not currently possible and will require a module update. We are looking into this and will hopefully be able to provide a resolution soon.

**Comment by endreigesund** [comment]
> Hi
> 
> May I know, before the parameter **Internet_Security_Enabled** becomes a variable, how could we enable this feature in a deployed CAF virtual wan ? I mean, route all spoke vnets Internet Traffic to Azure Firewall.

We decided to handle connections to hub outside the module. We can then use the inputs however we want to.

**Comment by krowlandson** [comment]
> ```terraform
> internet_security_enabled 
> ```

This would be the best way for now 👍🏻 

I was also just noting that we may also want to allow configuration of the `routing` entry, so I will also discuss this with the team.

**Comment by birdnathan** [comment]
> > Hi
> > May I know, before the parameter **Internet_Security_Enabled** becomes a variable, how could we enable this feature in a deployed CAF virtual wan ? I mean, route all spoke vnets Internet Traffic to Azure Firewall.
> 
> We decided to handle connections to hub outside the module. We can then use the inputs however we want to.
> 
> Set "enable_virtual_hub_connections" to false, and create them using your own code.

This, no other way at present. I tend to use az_api resources for anything VWAN, its a moving target

**Comment by KeynesLee** [comment]
We decided to handle connections to hub outside the module. We can then use the inputs however we want to.
> 
> Set "enable_virtual_hub_connections" to false, and create them using your own code.

This may not a good idea to us. We are making a massive transformation. Projects creates their subscriptions / vnets on Azure. The number of vnets grows rapidly.

We have leveraged the ability of CAF terraform code to 
1. peer the new created vnets to vwan hub 
    (**enable_private_dns_zone_virtual_network_link_on_hubs = true**)
2.  make virtual network links from 42 private DNS zones to the new created vnets.
    (**enable_private_dns_zone_virtual_network_link_on_spokes = true**)

What if we could we need to enable **Internet_security_enabled** by our own codes, all the changes rested when we apply CAF terraform code next time.

**Comment by krowlandson** [comment]
I am just working on getting a [PR](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/409) merged to introduce support for `optional()` types which will make it much easier for us to add features like this without introducing breaking changes for anyone else not needing this.

We will be using this in the next release as it should make upgrades much easier moving forward (_less breaking changes for existing customer code_).

I will ensure the feature requested in this issue gets put to the top of our backlog prioritisation once that is complete 👍🏻

**Comment by krowlandson** [comment]
Pulling link to reference from #518:
https://github.com/nthewara/tf-secured-virtualhub

**Comment by spotakash** [comment]
Hi @krowlandson 

It is blocker for another project too. 
Work-around, do this outside of module which add extra overhead and misses out inter-dependency. 
Here I am adding scenario why it is critical for module to support [INTERNET TRAFFIC](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_hub_connection#internet_security_enabled) as well as [PRIVATE TRAFFIC](https://github.com/nthewara/tf-secured-virtualhub) to have.

**Scenario because it is critical**:  Secured Hub Firewall is controlling all spoke, branch and internet traffic (using Firewall Policy). For Shared Service component VNETS (containing workload such as AzureBastion, Often Application Gateway (in centralized deployment), DevTest VNETs) will need seamless Internet Outbound connectivity (for Control plane operation as well as not overwhelming Secured Hub Firewall). Thus, there is need to use `Unsecured` ***INTERNET TRAFFIC*** under security configuration while `Secured by Azure Firewall` ***PRIVATE TRAFFIC***
Depicted Final Configuration

![image](https://user-images.githubusercontent.com/7689697/204569033-9f8efc20-dde3-418d-9cd5-642fbf1b7c91.png)


This could address possible by giving following option under `settings.connectivity.tf` 
```
secured_internet_private_spoke_vnet_ids = [ ]
secured_internet_spoke_vnet_ids = [ ]
secured_private_spoke_vnet_ids = [ ]
```
OR

```
spoke_virtual_network_resource_ids = {
    secured_internet_and_private = [ ] 
    secured_internet_only = [ ]
    secured_private_only = [ ]
}
```

**Comment by krowlandson** [comment]
Hi all... just wanted to give a quick update on this issue.

We have decided to focus on the original request from @birdnathan, allowing customisation of the `internet_security_enabled` setting. We are implementing this by adding a new `secure_spoke_virtual_network_resource_ids` attribute to the virtual hub configuration. This will effectively work in the same way as `spoke_virtual_network_resource_ids`.

Because of the way this setting works on the Azure side[^1], this will open up the flexibility needed to support the customer scenarios mentioned by both @birdnathan and @spotakash, without us needing to implement additional logic for handling an infinite number of route configuration options which may be needed by different customers.

[^1]: The `internet_security_enabled` setting effectively controls whether route entries for `0.0.0.0/0` in the propogated route tables are actually inherited by the connected virtual network.

To successfully complete configuration of Internet or private traffic to be "Secured by Azure Firewall" it is still necessary to correctly configure the default route table for each virtual hub, as described in the [guidance(https://github.com/nthewara/tf-secured-virtualhub) shared by @spotakash. This should be managed outside the module as this will offer the greatest flexibility around all the other possible options for configuring routing for virtual hub traffic.

We hope that this should provide the flexibility needed to implement more complicated scenarios without the module interfering.

To show some of this in action, please see the following:

- A code snippet showing spoke networks associated to the two inputs

  ![image](https://user-images.githubusercontent.com/12268562/207919078-0d3ba1c2-1b88-4f32-8bc8-6d17cc2db366.png)

  > **NOTE:** Under the hood, we are merging the two lists to determine the list of virtual networks to link to the virtual hub to avoid conflicts. We are de-duplicating this list to remove the risk of a customer adding the same ID to both, but will ensure that `internet_security_enabled = true` if the virtual network is in the `secure_spoke_virtual_network_resource_ids` list.

- See the above settings being successfully applied via the module

  ![image](https://user-images.githubusercontent.com/12268562/207919166-9de3c191-84fb-4eeb-ad8d-120f246a9c61.png)

- A working configuration in the Portal with both connections "Secured by Azure Firewall" for Internet and private traffic

  ![image](https://user-images.githubusercontent.com/12268562/207919268-17d98a65-7685-44ed-be52-57b5b26359d9.png)

- An example of Terrform reverting one of the connections back to `internet_security_enabled = false` as per the code, following an unwanted update in the Portal

  ![image](https://user-images.githubusercontent.com/12268562/207919586-4d80188c-26d5-4b3a-8e0c-68b216270b77.png)
