### ISSUE TITLE
Feature Request: Deploy out of the box policies to subscription

### ISSUE THREAD

**Issue by cveld** [Azure/terraform-azurerm-caf-enterprise-scale#548]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if it were possible to deploy the module against a single existing subscription. The goal is to enable some of the built-in policies. Maybe in future we want to grow to management groups but for now that is too soon.

**Comment by krowlandson** [comment]
Thank you for this ask @cveld

This is similar in nature to #420. In the same way, this won't be scalable with the module due to how the provider works against a specific Subscription per provider declaration.

As such, we cannot scale well when applying policies directly to Subscriptions.

Also from an ALZ design perspective, we always recommend creating policy assignments against Management Groups as this is part of the Subscription democratization principles. This ensures that no-one with Subscription-level access can remove policies due to the inheritance model. As such, we would advise that you always place a Subscription in a Management Group and assign governance policies to that Management Group.

Please also note that the reason for the recommended architecture of ALZ is to allow customer to grow. Putting all resources in a single Subscription will not scale and moving resources between Subscriptions isn't a fun experience.

I'm going to close this issue as this isn't something we will implement, but please re-open if you have further related questions.
