### ISSUE TITLE
Feature Request - Allow to custom peering connection name or use vnet name instead

### ISSUE THREAD

**Issue by KeynesLee** [Azure/terraform-azurerm-caf-enterprise-scale#563]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?
No

#### Describe the solution you'd like
CAF Terraform code generate a random connection for a peering. It makes we hard to realize what does the connection (peering-xxxxx) indicates to which vnets, then it will be not easy read in Virtual Hub security connection. Like below figure.
Could we be allowed to custom peering connection name or use vnet name instead ?
  
![image](https://user-images.githubusercontent.com/11400334/208331303-0439706e-8dd1-4a5a-9f35-a0434b823423.png)

**Comment by krowlandson** [comment]
Thank you for the question @KeynesLee 

We currently use the following pattern for naming virtual hub connections:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/d06fbad46de49f06e6c0b14f3214545907831124/modules/connectivity/locals.tf#L1697

The reason we use the `spoke_resource_id` is because this guarantees global uniqueness. The `uuidv5` function then converts this to a deterministic GUID ensuring that it has a fixed length within the [naming limits](https://github.com/hashicorp/terraform-provider-azurerm/blob/b0c897055329438be6a3a159f6ffac4e1ce958f2/internal/services/network/validate/virtual_hub_connection_name.go#L11-L13) of the resource type.

Unfortunately for many customers, using a "Virtual Network Name" would result in conflicts where the same name is used in multiple landing zones. This is quite common in automated Subscription vending scenarios, where all Subscriptions get a pre-provisioned virtual network with a standardised name.

I can look at the option of adding support to set a custom name as we recently did for [virtual network peerings](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/401), but please note that this will require significant additional customer code to implement as seen in the PR evidence, and that changing the name of an existing virtual hub connection will result in a new connection being created (therefore resulting in downtime for that spoke).

Please let me know your thoughts.
