### ISSUE TITLE
Bug Report - Documentation error ?  enable_monitoring_for_arc disappeared from configure_management_resources

### ISSUE THREAD

**Issue by cbezenco** [Azure/terraform-azurerm-caf-enterprise-scale#583]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
NA doc error
**azure provider**:
NA doc error
**module**:

### Description
As I was upgrading to release 3.1.2, I reviewed my configuration settings to update the latest configuration variables.

When reviewing [configuration_management_resources](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_management_resources), I was surprised to see that enable_monitoring_for_arc has disappeared. I did a search on the repo/docs but I could not find any mention of deprecation for this variables. 

Also noted additional variable missing : enable_solution_for_azure_activity 

Is this a documentation error or did I miss the deprecation announcement ? 

#### Describe the bug
Documentation error - configure_management_resources - variables missing ?

locals.configuration_management_resources.settings.log_analytics.config.enable_monitoring_for_arc
locals.configuration_management_resources.settings.log_analytics.config.enable_solution_for_azure_activity 

NA

NA

**Comment by krowlandson** [comment]
Hi @cbezenco... this was removed in release `v3.0.0` as noted in the [upgrade guide](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Upgrade-from-v2.4.1-to-v3.0.0#resource-type-azurerm_policy_assignment).

This policy is now covered within the `Deploy-VM-Monitoring` assignment which uses a built-in policy.

**Comment by cbezenco** [comment]
Sorry, I did search the repo for "enable_monitoring_for_arc". I assume it is similar for "enable_solution_for_azure_activity" ? 

I was under the impression that the object validation would raise an error during terraform plan/apply ... 

I have been running 3.0.0 for a few weeks now but I did not raise any issue although I had this deprecated variable defined in my config files. Do I need to run a specific terraform command to check my config files are up to date ?

**Comment by krowlandson** [comment]
The best place to look is in the release notes (and upgrade guides for major releases) as we detail the changes in these.

With the introduction of `optional()` types, we no longer need customers to make code changes when we add new attributes to an input as long as you are happy with the defaults.

Similarly, Terraform has always discarded unused properties without error which is why your configuration was OK following the upgrade.

Because of this, we are trying to make a habit of calling out input changes within the release notes in a dedicated section.

I'm not aware of a Terraform command to check for this (I don't think `terraform validate` checks to this depth).

Hope this helps?
