### ISSUE TITLE
Configure diagnostic settings for VPN Gateway

### ISSUE THREAD

**Issue by cveld** [Azure/terraform-azurerm-caf-enterprise-scale#590]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the diagnostic settings for a VPN Gateway resource are not configured by the module out of the box.
Desired would be to get this included.

**Comment by krowlandson** [comment]
@cveld - we currently manage diagnostic settings across all (supported) resources using policy for consistency across the reference implementations (Terraform, Bicep and ARM) but this seems a fair ask.

@lachaves is already looking at enabling this for management groups, and this is something we should consider for all resource types created by the module.

**Comment by krowlandson** [comment]
@cveld, just to clarify... are you asking us to explicitly add diagnostic settings to the VPN gateway resource using Terraform instead of relying on policy to add this via remediation after creation?

If so, does this ask extend to other resource types?

**Comment by matt-FFFFFF** [comment]
@cveld the ALZ guidance is to have a single central LA workspace for the platform. Within a landing zone subscription it is possible to deploy additional workspaces/application insights in order to capture app specific logs and metrics.

In your architecture, where is the VPN gateway resource located - in which subscription and under which management group?

If the deploy-resource-diag policy does not support the resource you require, then please raise an issue upstream on [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale) and we can add it.
