### ISSUE TITLE
Feature Request: Policies for Azure Monitor Agent and data collection rules

### ISSUE THREAD

**Issue by adhodgson1** [Azure/terraform-azurerm-caf-enterprise-scale#692]
### Community Note
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Has there been any thought to providing policy definitions/assignments for installing/managing the Azure Monitor agent solution on virtual machines? The current policies install the older Log Analytics agent (MMA) which is being deprecated next year.

**Comment by jtracey93** [comment]
Hey @adhodgson1, thanks for the issue here. 

We are indeed working on this as we speak and are tracking in https://github.com/Azure/Enterprise-Scale/issues/1055

We are working closely with the AMA product group to ensure everything is in place so we can move to this in all ALZ implementations soon. 

I’ll close this issue out as tracked on the issue above 👍
