### ISSUE TITLE
Bug Report / Support Request: Azure Active Directory Domain Services  (ADDS) deployment

### ISSUE THREAD

**Issue by mlomat** [Azure/terraform-azurerm-caf-enterprise-scale#814]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hello team, This is much more question / looking for recommendation where we should deploy AD DS in Enterprise Scale. From my point of view, natural place is Identity subscription, but deployment is not allowing to separate network resources into different resource group / subscription. So everything is landing in same subscription. From caf-enterprise-scale we have policy which is blocking deployment of subnets without NSG and public IPs, which is not allowing to deploy AD DS. 

Questions: 
1. Is it on purpose, to deploy AD DS somewhere else?
2. Do we want to extend ES to support this use case? E.g. config to automatically deploy AD DS in identity sub. 
3. Do we just want to change policy on Identity to have exception for AD DS. 

Thanks! 

#### Steps to Reproduce

1.Deploy AD DS in Identity Subscription

**Comment by hlokensgard** [comment]
I have implemented this @mlomat  :) 
Solved by doing the following (using terraform for everything): 
- Create an exclusion on the identity archetype for public IP, since AADDS demands an public IP. 
- Create a dedicated virtual network for the AADDS resources
- Create an management VM (could be in the same virtual network or any other virtual network, based on your design)
- Peer the dedicated virtual network to every other virtual network. You can't route the traffic through the firewall using UDR, not supported (or not supported when I was implementing it). See here for more information about the network configuration: https://learn.microsoft.com/en-us/azure/active-directory-domain-services/network-considerations
- Deploy the AADDS resource
- Create Entra ID groups for RBAC
- I will also recommend creating an Azure Policy for automatically join VMs to the AADDS. Makes management easier. 

If you are using terraform you can easily deploy subnet with the NSG, not sure how it works if you do it through the portal or Bicep.

**Comment by mlomat** [comment]
Hi @hlokensgard, thanks for instruction ;) I know how to achieve it. Would be nice to have it out of the box and will be happy if @matt-FFFFFF or someone from MSFT team can comment. Thanks!

**Comment by matt-FFFFFF** [comment]
Hi @mlomat 

I think @hlokensgard's suggestion is a good one here.

Essentially you have to create an exemption/exclusion for the policy that is preventing the deployment.

We don't have plans to extend this module to support AADDS. Let me know if you need anything else.

**Comment by mlomat** [comment]
Thanks @matt-FFFFFF ok I understand, no issue from my side. I will create exception.
